// ui/src/views/Login.svelte
<script>
  import { api, setToken, ApiError } from "../lib/api.js";

  let { onauth } = $props();

  let accessKey = $state("");
  let secretKey = $state("");
  let error = $state("");
  let busy = $state(false);
  let showSecret = $state(false);
  let capsOn = $state(false);

  async function submit(e) {
    e.preventDefault();
    error = "";
    const id = accessKey.trim();
    const secret = secretKey;
    if (!id || !secret) {
      error = "Enter your access key and secret key.";
      return;
    }
    busy = true;
    // The management API authenticates with a Bearer token of the form
    // `<access-key>.<secret>`. Build it from the two fields, set it
    // provisionally, then verify against an admin-gated endpoint (/overview
    // requires the administrator role, so a 403 means it authenticated but is
    // not an admin).
    setToken(`${id}.${secret}`);
    try {
      await api.overview();
      onauth();
    } catch (err) {
      setToken("");
      if (err instanceof ApiError && err.status === 403) {
        error = "That credential works, but it is not an administrator.";
      } else if (err instanceof ApiError && err.status === 401) {
        error = "Access key or secret key is incorrect.";
      } else {
        error = err.message || "Could not sign in.";
      }
    } finally {
      busy = false;
    }
  }

  // Surface a caps-lock warning while typing the secret, since it is masked by default.
  function onSecretKey(e) {
    if (typeof e.getModifierState === "function") {
      capsOn = e.getModifierState("CapsLock");
    }
  }
</script>

<div class="login">
  <form class="login-card" onsubmit={submit}>
    <h1><span class="brand"><span class="dot"></span> Cairn</span></h1>
    <p class="subtitle">Sign in to the management console</p>

    {#if error}
      <div class="notice danger" role="alert">{error}</div>
    {/if}

    <div class="field">
      <label for="ak">Access key</label>
      <input
        id="ak"
        type="text"
        placeholder="Your admin access key"
        bind:value={accessKey}
        autocomplete="username"
        autocapitalize="off"
        autocorrect="off"
        spellcheck="false" />
    </div>

    <div class="field">
      <label for="sk">Secret key</label>
      <div class="secret-row">
        {#if showSecret}
          <input
            id="sk"
            type="text"
            placeholder="Your admin secret key"
            bind:value={secretKey}
            onkeyup={onSecretKey}
            autocomplete="off"
            autocapitalize="off"
            autocorrect="off"
            spellcheck="false" />
        {:else}
          <input
            id="sk"
            type="password"
            placeholder="Your admin secret key"
            bind:value={secretKey}
            onkeyup={onSecretKey}
            autocomplete="current-password" />
        {/if}
        <button
          type="button"
          class="btn reveal"
          aria-pressed={showSecret}
          onclick={() => (showSecret = !showSecret)}>
          {showSecret ? "Hide" : "Show"}
        </button>
      </div>
      {#if capsOn}
        <p class="caps-hint" role="status">Caps Lock is on.</p>
      {/if}
    </div>

    <button class="primary full" type="submit" disabled={busy} aria-busy={busy}>
      {busy ? "Signing in…" : "Sign in"}
    </button>
    <p class="hint">
      Enter your administrator access key and secret key. The same credentials work
      with the S3 API and the CLI. They are stored in this browser only.
    </p>
  </form>
</div>

<style>
  /* Quiet the page background: a flat surface reads as a sign-in screen, not an ad. The shared
     .login glow is overridden here. */
  .login {
    background: var(--bg);
  }
  .secret-row {
    display: flex;
    gap: 8px;
    align-items: stretch;
  }
  .secret-row input {
    flex: 1;
    min-width: 0;
  }
  .secret-row .reveal {
    flex-shrink: 0;
  }
  .caps-hint {
    margin: 6px 0 0;
    font-size: 0.85rem;
    font-weight: 500;
    color: var(--warning-ink);
  }
  .hint {
    margin-top: 1rem;
    font-size: 0.85rem;
    line-height: 1.55;
    color: var(--text-muted);
  }
</style>

// web/src/views/login.tsx
// Sign-in screen for the admin console. Renders standalone (no AppShell):
// the management API authenticates with a Bearer token of the form
// `<access-key>.<secret>`, which the auth provider assembles and verifies
// against an admin-gated endpoint before letting the session in.

import {
  useEffect,
  useId,
  useRef,
  useState,
  type FormEvent,
  type KeyboardEvent,
} from "react";
import { Navigate, useLocation, useNavigate } from "react-router";
import { Eye, EyeOff } from "lucide-react";
import { errorMessage } from "@/lib/api";
import { useAuth } from "@/providers/auth-provider";
import { FieldError } from "@/components/field-error";
import { Button } from "@/components/primitives/button";
import { Card, CardContent, CardHeader } from "@/components/primitives/card";
import { Input } from "@/components/primitives/input";
import { Label } from "@/components/primitives/label";

export function Login() {
  const { authed, login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  // Where to land after signing in: the page a session-expiry bounce came from
  // (captured by RequireAuth), otherwise the overview.
  const from =
    (location.state as { from?: string } | null)?.from ?? "/overview";

  const [accessKey, setAccessKey] = useState("");
  const [secretKey, setSecretKey] = useState("");
  const [showSecret, setShowSecret] = useState(false);
  const [capsOn, setCapsOn] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const accessKeyId = useId();
  const secretKeyId = useId();
  const capsHintId = useId();

  const accessKeyRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    accessKeyRef.current?.focus();
  }, []);

  // Surface a Caps Lock warning while typing the secret, since it is masked
  // by default and a wrong-case secret fails with no other clue.
  function onSecretModifier(e: KeyboardEvent<HTMLInputElement>) {
    if (typeof e.getModifierState === "function") {
      setCapsOn(e.getModifierState("CapsLock"));
    }
  }

  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    const id = accessKey.trim();
    if (!id || !secretKey) {
      setError("Enter your access key and secret key.");
      return;
    }
    setBusy(true);
    try {
      await login(id, secretKey);
      navigate(from, { replace: true });
    } catch (err) {
      setError(errorMessage(err, "Could not sign in."));
    } finally {
      setBusy(false);
    }
  }

  if (authed) {
    return <Navigate to={from} replace />;
  }

  return (
    <main className="flex min-h-svh items-center justify-center bg-background px-4 py-10">
      <Card className="w-full max-w-sm">
        <CardHeader className="gap-1.5">
          <div className="mb-2 flex items-center gap-2">
            <span
              aria-hidden="true"
              className="size-4 rounded-[4px] bg-foreground"
            />
            <span className="text-sm font-semibold">Cairn</span>
          </div>
          <h1 className="text-lg font-semibold tracking-tight">
            Sign in to the console
          </h1>
          <p className="text-sm text-muted-foreground">
            Manage buckets, users, and storage on this node.
          </p>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="space-y-4" noValidate>
            <FieldError>{error}</FieldError>

            <div className="space-y-2">
              <Label htmlFor={accessKeyId}>Access key</Label>
              <Input
                id={accessKeyId}
                ref={accessKeyRef}
                type="text"
                value={accessKey}
                onChange={(e) => setAccessKey(e.target.value)}
                placeholder="Your admin access key"
                autoComplete="username"
                autoCapitalize="off"
                autoCorrect="off"
                spellCheck={false}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor={secretKeyId}>Secret key</Label>
              <div className="relative">
                <Input
                  id={secretKeyId}
                  type={showSecret ? "text" : "password"}
                  value={secretKey}
                  onChange={(e) => setSecretKey(e.target.value)}
                  onKeyDown={onSecretModifier}
                  onKeyUp={onSecretModifier}
                  placeholder="Your admin secret key"
                  autoComplete="current-password"
                  autoCapitalize="off"
                  autoCorrect="off"
                  spellCheck={false}
                  className="pr-10"
                  aria-describedby={capsOn ? capsHintId : undefined}
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon-sm"
                  className="absolute top-1/2 right-1 size-8 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                  aria-pressed={showSecret}
                  aria-label={
                    showSecret ? "Hide secret key" : "Show secret key"
                  }
                  onClick={() => setShowSecret((v) => !v)}
                >
                  {showSecret ? (
                    <EyeOff aria-hidden="true" className="size-4" />
                  ) : (
                    <Eye aria-hidden="true" className="size-4" />
                  )}
                </Button>
              </div>
              {capsOn ? (
                <p
                  id={capsHintId}
                  role="status"
                  className="text-[13px] text-warning"
                >
                  Caps Lock is on.
                </p>
              ) : null}
            </div>

            <Button
              type="submit"
              className="w-full"
              disabled={busy}
              aria-busy={busy}
            >
              {busy ? "Signing in…" : "Sign in"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </main>
  );
}
