// ui/src/components/permission-builder.tsx
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { Info } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { FieldError } from "@/components/field-error";
import { Input } from "@/components/ui/input";
import { JsonEditor } from "@/components/json-editor";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Skeleton } from "@/components/ui/skeleton";
import {
  ACTION_GLOSS,
  ACTION_GROUPS,
  LEVELS,
  LEVEL_ACTIONS,
  actionSummary,
  advancedToPolicy,
  grantsAccess,
  policyToPreset,
  presetToPolicy,
  pretty,
  validate,
  type Level,
  type PolicyDoc,
  type Scope,
} from "@/lib/policy";
import { cn } from "@/lib/utils";

type Mode = "builder" | "split" | "code";

interface BuilderModel {
  scope: Scope;
  pickedBuckets: string[];
  level: Level;
  advanced: boolean;
  pickedActions: string[];
}

function docFor(m: BuilderModel): PolicyDoc {
  return m.advanced
    ? advancedToPolicy({
        scope: m.scope,
        buckets: m.pickedBuckets,
        actions: m.pickedActions,
      })
    : presetToPolicy({ scope: m.scope, buckets: m.pickedBuckets, level: m.level });
}

function grantsNothing(m: BuilderModel): boolean {
  return (
    (m.scope === "specific" && m.pickedBuckets.length === 0) ||
    (m.advanced && m.pickedActions.length === 0)
  );
}

/**
 * A policy editor with two synced views: a visual Builder (plain-language
 * choices) and a JSON Code editor, plus Split where editing either side
 * updates the other. Emits the current policy doc via `onChange(docOrNull)` —
 * null means the JSON is invalid OR the selection grants nothing, so the
 * parent disables save and shows why.
 */
export function PermissionBuilder({
  buckets,
  bucketsLoading = false,
  initial = null,
  onChange,
}: {
  buckets: string[];
  bucketsLoading?: boolean;
  initial?: PolicyDoc | null;
  onChange: (doc: PolicyDoc | null) => void;
}) {
  const uid = useId();

  // `initial` is a one-time seed read at mount; parents remount via key= when
  // the target changes, so capturing it once is intentional.
  const seed = useRef(initial).current;
  const seedPreset = useMemo(() => (seed ? policyToPreset(seed) : null), [seed]);

  // Default to the Builder for new users; editing an existing policy starts in
  // Split so the JSON they may already understand stays visible.
  const [mode, setMode] = useState<Mode>(seed ? "split" : "builder");
  const [model, setModel] = useState<BuilderModel>(() =>
    seedPreset?.recognized
      ? {
          scope: seedPreset.scope,
          pickedBuckets: seedPreset.buckets,
          level: seedPreset.level,
          advanced: false,
          pickedActions: [...LEVEL_ACTIONS[seedPreset.level]],
        }
      : {
          scope: "all",
          pickedBuckets: [],
          level: "read",
          advanced: false,
          pickedActions: [...LEVEL_ACTIONS.read],
        },
  );
  // True when the JSON is an unrecognized (but valid) doc — JSON authoritative.
  const [custom, setCustom] = useState(!!seed && !seedPreset?.recognized);
  const [rawText, setRawText] = useState(() =>
    seed ? pretty(seed) : pretty(docFor(model)),
  );
  const [jsonError, setJsonError] = useState<string | null>(null);
  const [bucketFilter, setBucketFilter] = useState("");

  // Emit the initial doc once on mount (or null if the seed grants nothing).
  const emittedOnce = useRef(false);
  useEffect(() => {
    if (emittedOnce.current) return;
    emittedOnce.current = true;
    if (custom) {
      const v = validate(rawText);
      onChange(v.ok && grantsAccess(v.doc) ? v.doc : null);
    } else {
      const doc = docFor(model);
      onChange(!grantsNothing(model) && grantsAccess(doc) ? doc : null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Builder edits → apply the new model, regenerate JSON, emit.
  function applyBuilder(next: Partial<BuilderModel>) {
    const m: BuilderModel = { ...model, ...next };
    setModel(m);
    setCustom(false);
    setJsonError(null);
    const doc = docFor(m);
    setRawText(pretty(doc));
    onChange(!grantsNothing(m) && grantsAccess(doc) ? doc : null);
  }

  // Code edits → validate, re-derive the builder (best-effort), emit.
  function fromCode(text: string) {
    setRawText(text);
    const v = validate(text);
    if (!v.ok) {
      setJsonError(v.error);
      onChange(null);
      return;
    }
    setJsonError(null);
    const p = policyToPreset(v.doc);
    if (p.recognized) {
      setCustom(false);
      setModel({
        scope: p.scope,
        pickedBuckets: p.buckets,
        level: p.level,
        advanced: false,
        pickedActions: [...LEVEL_ACTIONS[p.level]],
      });
    } else {
      setCustom(true);
    }
    onChange(grantsAccess(v.doc) ? v.doc : null);
  }

  function switchMode(m: Mode) {
    setMode(m);
    // Re-emit from whichever side is now authoritative.
    if (m === "code") fromCode(rawText);
  }

  const noBuckets = model.scope === "specific" && model.pickedBuckets.length === 0;
  const noActions = model.advanced && model.pickedActions.length === 0;
  const builderGrantsNothing = !custom && (noBuckets || noActions);

  // The preset levels grant wildcard patterns (s3:Get*) the per-action gloss
  // can't translate, so each level carries its own plain-language phrasing.
  const LEVEL_PHRASES: Record<Level, string[]> = {
    read: ["See the list of files in a bucket", "Download files"],
    write: [
      "See the list of files in a bucket",
      "Download files",
      "Upload and overwrite files",
      "Delete files",
      "Cancel an in-progress large upload",
    ],
    full: ["Do everything S3 allows on the chosen buckets"],
  };
  const allowPhrases = model.advanced
    ? actionSummary(model.pickedActions)
    : LEVEL_PHRASES[model.level];
  const scopePhrase =
    model.scope === "all"
      ? "every bucket on this server"
      : model.pickedBuckets.length === 0
        ? "no buckets yet"
        : model.pickedBuckets.length === 1
          ? `the bucket ${model.pickedBuckets[0]}`
          : `${model.pickedBuckets.length} buckets`;

  const filter = bucketFilter.trim().toLowerCase();
  const filteredBuckets = filter
    ? buckets.filter((b) => b.toLowerCase().includes(filter))
    : buckets;
  const allFilteredPicked =
    filteredBuckets.length > 0 &&
    filteredBuckets.every((b) => model.pickedBuckets.includes(b));

  function toggleSelectAll() {
    if (allFilteredPicked) {
      const drop = new Set(filteredBuckets);
      applyBuilder({
        pickedBuckets: model.pickedBuckets.filter((b) => !drop.has(b)),
      });
    } else {
      applyBuilder({
        pickedBuckets: [...new Set([...model.pickedBuckets, ...filteredBuckets])],
      });
    }
  }

  const showBuilder = mode !== "code";
  const showCode = mode !== "builder";

  return (
    <div>
      {/* View switch: a toggle group, not a tab-panel set. */}
      <div
        role="group"
        aria-label="Policy editor view"
        className="mb-4 flex w-full rounded-lg bg-muted p-1 sm:inline-flex sm:w-auto"
      >
        {(
          [
            ["builder", "Builder"],
            ["split", "Split"],
            ["code", "Code"],
          ] as [Mode, string][]
        ).map(([m, label]) => (
          <button
            key={m}
            type="button"
            aria-pressed={mode === m}
            onClick={() => switchMode(m)}
            className={cn(
              "flex-1 rounded-md px-3.5 py-1.5 text-sm font-medium transition-colors sm:flex-none",
              mode === m
                ? "border bg-background text-foreground"
                : "text-muted-foreground hover:text-foreground",
            )}
          >
            {label}
          </button>
        ))}
      </div>

      <div className={cn("min-w-0", mode === "split" && "grid items-start gap-5 lg:grid-cols-2")}>
        {showBuilder ? (
          <div className="min-w-0 space-y-5">
            {custom ? (
              <Alert role="status">
                <Info aria-hidden="true" />
                <AlertDescription>
                  This policy isn't one the visual builder recognizes, so edit it
                  as JSON in the Code view. Changing a control below will replace
                  it.
                </AlertDescription>
              </Alert>
            ) : null}

            <fieldset className="space-y-2.5">
              <legend className="mb-1.5 text-[13px] font-medium text-muted-foreground">
                Which buckets
              </legend>
              <RadioGroup
                value={model.scope}
                onValueChange={(v) => applyBuilder({ scope: v as Scope })}
                className="flex flex-wrap gap-2"
              >
                {(
                  [
                    ["all", "All buckets"],
                    ["specific", "Specific buckets"],
                  ] as [Scope, string][]
                ).map(([s, label]) => (
                  <Label
                    key={s}
                    className={cn(
                      // The radio is sr-only, so surface ITS focus ring on the
                      // visible pill — otherwise keyboard focus is invisible here.
                      "flex cursor-pointer items-center gap-2 rounded-full border px-3.5 py-2 text-sm has-[:focus-visible]:border-ring has-[:focus-visible]:ring-[3px] has-[:focus-visible]:ring-ring/50",
                      model.scope === s
                        ? "border-foreground"
                        : "text-muted-foreground",
                    )}
                  >
                    <RadioGroupItem value={s} className="sr-only" />
                    {label}
                  </Label>
                ))}
              </RadioGroup>

              {model.scope === "specific" ? (
                bucketsLoading ? (
                  <div className="space-y-2 rounded-md border p-3" role="status" aria-label="Loading buckets">
                    <Skeleton className="h-4 w-2/3" />
                    <Skeleton className="h-4 w-1/2" />
                  </div>
                ) : buckets.length === 0 ? (
                  <p className="rounded-md border bg-muted/50 px-3 py-2.5 text-[13px] text-muted-foreground" role="status">
                    There are no buckets yet. Create a bucket first, then come
                    back to scope this user to it.
                  </p>
                ) : (
                  <div className="space-y-2">
                    {buckets.length > 6 ? (
                      <div className="flex items-center gap-2">
                        <Input
                          type="search"
                          value={bucketFilter}
                          onChange={(e) => setBucketFilter(e.target.value)}
                          placeholder="Filter buckets"
                          aria-label="Filter buckets"
                          className="h-8"
                        />
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={toggleSelectAll}
                          disabled={filteredBuckets.length === 0}
                          className="shrink-0"
                        >
                          {allFilteredPicked ? "Clear shown" : "Select shown"}
                        </Button>
                      </div>
                    ) : null}
                    <div
                      role="group"
                      aria-label="Buckets this user may use"
                      className="max-h-44 space-y-1 overflow-auto rounded-md border p-2"
                    >
                      {filteredBuckets.length === 0 ? (
                        <p className="px-1 py-0.5 text-[13px] text-muted-foreground">
                          No buckets match “{bucketFilter}”.
                        </p>
                      ) : (
                        filteredBuckets.map((b) => (
                          <Label
                            key={b}
                            className="flex cursor-pointer items-center gap-2 rounded px-1.5 py-1 font-normal hover:bg-accent"
                          >
                            <Checkbox
                              checked={model.pickedBuckets.includes(b)}
                              onCheckedChange={() =>
                                applyBuilder({
                                  pickedBuckets: model.pickedBuckets.includes(b)
                                    ? model.pickedBuckets.filter((x) => x !== b)
                                    : [...model.pickedBuckets, b],
                                })
                              }
                            />
                            <span className="font-mono text-[13px]">{b}</span>
                          </Label>
                        ))
                      )}
                    </div>
                    {noBuckets ? (
                      <FieldError>
                        Pick at least one bucket, or switch to All buckets. With
                        none selected this user gets no access.
                      </FieldError>
                    ) : (
                      <p className="text-[13px] text-muted-foreground">
                        {model.pickedBuckets.length} selected.
                      </p>
                    )}
                  </div>
                )
              ) : null}
            </fieldset>

            <fieldset className="space-y-2.5">
              <legend className="mb-1.5 text-[13px] font-medium text-muted-foreground">
                What they can do
              </legend>
              <Label className="flex cursor-pointer items-center gap-2 font-normal">
                <Checkbox
                  checked={model.advanced}
                  onCheckedChange={(v) => {
                    const on = v === true;
                    applyBuilder({
                      advanced: on,
                      pickedActions:
                        on && model.pickedActions.length === 0
                          ? [...LEVEL_ACTIONS[model.level]]
                          : model.pickedActions,
                    });
                  }}
                />
                <span className="text-sm">Advanced: pick individual actions</span>
              </Label>

              {!model.advanced ? (
                <RadioGroup
                  value={model.level}
                  onValueChange={(v) => {
                    const level = v as Level;
                    applyBuilder({
                      level,
                      pickedActions: model.advanced
                        ? [...LEVEL_ACTIONS[level]]
                        : model.pickedActions,
                    });
                  }}
                  className="gap-2"
                >
                  {LEVELS.map((l) => (
                    <Label
                      key={l.id}
                      className={cn(
                        "flex cursor-pointer flex-col items-start gap-0.5 rounded-lg border px-3.5 py-2.5",
                        model.level === l.id ? "border-foreground" : "",
                      )}
                    >
                      <span className="flex items-center gap-2 text-sm font-medium">
                        <RadioGroupItem value={l.id} />
                        {l.label}
                      </span>
                      <span className="pl-6 text-[13px] font-normal text-muted-foreground">
                        {l.hint}
                      </span>
                    </Label>
                  ))}
                </RadioGroup>
              ) : (
                <div className="space-y-3">
                  <div className="grid gap-x-5 gap-y-3 sm:grid-cols-2">
                    {ACTION_GROUPS.map((g) => (
                      <div key={g.label} className="space-y-1">
                        <p className="text-[13px] font-medium text-muted-foreground">
                          {g.label}
                        </p>
                        {g.actions.map((a) => (
                          <Label
                            key={a}
                            className="flex cursor-pointer items-start gap-2 rounded px-1 py-1 font-normal hover:bg-accent"
                          >
                            <Checkbox
                              className="mt-0.5"
                              checked={model.pickedActions.includes(a)}
                              onCheckedChange={() =>
                                applyBuilder({
                                  pickedActions: model.pickedActions.includes(a)
                                    ? model.pickedActions.filter((x) => x !== a)
                                    : [...model.pickedActions, a],
                                })
                              }
                            />
                            <span className="flex flex-col leading-tight">
                              <span className="text-sm">{ACTION_GLOSS[a] ?? a}</span>
                              <span className="font-mono text-[11px] text-muted-foreground">
                                {a}
                              </span>
                            </span>
                          </Label>
                        ))}
                      </div>
                    ))}
                  </div>
                  {noActions ? (
                    <FieldError>
                      Pick at least one action. With none selected this user gets
                      no access.
                    </FieldError>
                  ) : null}
                </div>
              )}
            </fieldset>

            {/* Running, plain-language summary so the JSON is never the only
                thing explaining intent. */}
            {!custom ? (
              <div
                aria-live="polite"
                className="rounded-lg border bg-muted/50 px-3.5 py-3"
              >
                <p className="text-[13px] font-medium text-muted-foreground">
                  This lets the user
                </p>
                {builderGrantsNothing ? (
                  <p className="mt-1 text-sm text-muted-foreground">
                    Nothing yet.{" "}
                    {noBuckets ? "Pick at least one bucket" : "Pick at least one action"}{" "}
                    to grant access.
                  </p>
                ) : (
                  <>
                    <ul className="mt-1.5 list-disc space-y-0.5 pl-5 text-sm">
                      {allowPhrases.map((phrase) => (
                        <li key={phrase}>{phrase}</li>
                      ))}
                    </ul>
                    <p className="mt-1.5 text-[13px] text-muted-foreground">
                      on {scopePhrase}.
                    </p>
                  </>
                )}
              </div>
            ) : null}
          </div>
        ) : null}

        {showCode ? (
          <div className={cn("min-w-0", mode === "code" ? "" : "lg:sticky lg:top-20")}>
            <Label
              htmlFor={`${uid}-json`}
              className="mb-1.5 text-[13px] text-muted-foreground"
            >
              Policy JSON
            </Label>
            <JsonEditor
              value={rawText}
              onChange={fromCode}
              error={jsonError}
              label="Policy JSON"
              rows={mode === "code" ? 16 : 14}
            />
          </div>
        ) : null}
      </div>
    </div>
  );
}

// ui/src/components/PermissionBuilder.svelte
<script>
  // A policy editor with two synced views: a visual Builder (the default, where most choices are
  // plain language) and a JSON Code editor, plus Split (side-by-side) where editing either side
  // updates the other. Emits the current policy doc via `onchange(docOrNull)` — null means the JSON
  // is invalid OR the selection grants nothing actionable, so the parent disables save and shows why.
  import {
    LEVELS,
    LEVEL_ACTIONS,
    ACTION_GROUPS,
    ACTION_GLOSS,
    actionSummary,
    presetToPolicy,
    advancedToPolicy,
    policyToPreset,
    grantsAccess,
    validate,
    pretty,
  } from "../lib/policy.js";

  let {
    buckets = [],
    initial = null,
    bucketsLoading = false,
    onchange = () => {},
  } = $props();

  // `initial` is a one-time seed read at mount; the parent remounts via {#key user.id} when it
  // changes, so capturing it once here is intentional. Read it through a closure so the compiler
  // doesn't treat the prop as a live reactive dependency of the initial $state values.
  const seed = (() => initial)();

  // Default to the Builder for new users (no initial policy). When editing an existing policy we
  // start in Split so the JSON they may already understand stays visible.
  let mode = $state(seed ? "split" : "builder"); // "builder" | "split" | "code"
  let advanced = $state(false);
  let scope = $state("all"); // "all" | "specific"
  let pickedBuckets = $state([]);
  let level = $state("read");
  let pickedActions = $state([...LEVEL_ACTIONS.read]);
  let custom = $state(false); // JSON is an unrecognized (but valid) doc
  let rawText = $state(pretty(presetToPolicy({ scope: "all", level: "read" })));
  let error = $state(""); // JSON parse/validation error (Code side)
  let bucketFilter = $state("");

  const uid = Math.random().toString(36).slice(2, 8);

  // Seed from an existing policy (UserDetail edit).
  if (seed) {
    rawText = pretty(seed);
    const p = policyToPreset(seed);
    if (p.recognized) {
      scope = p.scope;
      pickedBuckets = p.buckets;
      level = p.level;
    } else {
      custom = true;
    }
  }

  // Current doc derived from the visual model (used by the Builder side and the summary).
  let builderDoc = $derived(
    advanced
      ? advancedToPolicy({ scope, buckets: pickedBuckets, actions: pickedActions })
      : presetToPolicy({ scope, buckets: pickedBuckets, level }),
  );

  // True when the visual selection cannot grant anything (specific scope, nothing picked, or no
  // actions in advanced mode). Drives the inline block and the emitted-null guard.
  let noBuckets = $derived(scope === "specific" && pickedBuckets.length === 0);
  let noActions = $derived(advanced && pickedActions.length === 0);
  let builderGrantsNothing = $derived(!custom && (noBuckets || noActions));

  // Plain-language "what this allows" summary for the Builder.
  let allowPhrases = $derived(
    advanced ? actionSummary(pickedActions) : actionSummary(LEVEL_ACTIONS[level]),
  );
  let scopePhrase = $derived(
    scope === "all"
      ? "every bucket on this server"
      : pickedBuckets.length === 0
        ? "no buckets yet"
        : pickedBuckets.length === 1
          ? `the bucket ${pickedBuckets[0]}`
          : `${pickedBuckets.length} buckets`,
  );

  let filteredBuckets = $derived(
    bucketFilter.trim()
      ? buckets.filter((b) => b.toLowerCase().includes(bucketFilter.trim().toLowerCase()))
      : buckets,
  );
  let allFilteredPicked = $derived(
    filteredBuckets.length > 0 && filteredBuckets.every((b) => pickedBuckets.includes(b)),
  );

  // Emit the initial doc once on mount (or null if the seed grants nothing).
  emit();

  // Compute + emit the current doc. When the JSON is a custom (unrecognized) doc it stays
  // authoritative; otherwise the visual model is. A selection that grants nothing emits null so the
  // parent blocks Create with a clear reason.
  function emit() {
    if (custom) {
      // Custom JSON authored in the Code/Split view is authoritative — re-validate and emit it.
      const v = validate(rawText);
      onchange(v.ok && grantsAccess(v.doc) ? v.doc : null);
      return;
    }
    if (builderGrantsNothing || !grantsAccess(builderDoc)) {
      onchange(null);
      return;
    }
    onchange(builderDoc);
  }

  // Builder edits → regenerate JSON, emit.
  function fromBuilder() {
    custom = false;
    error = "";
    rawText = pretty(builderDoc);
    emit();
  }

  // Code edits → validate, re-derive the builder (best-effort), emit.
  function fromCode() {
    const v = validate(rawText);
    if (!v.ok) {
      error = v.error;
      onchange(null);
      return;
    }
    error = "";
    const p = policyToPreset(v.doc);
    if (p.recognized) {
      custom = false;
      advanced = false;
      scope = p.scope;
      pickedBuckets = p.buckets;
      level = p.level;
    } else {
      custom = true;
    }
    // Even a valid, parseable doc can grant nothing (empty resources). Guard the same way.
    onchange(grantsAccess(v.doc) ? v.doc : null);
  }

  function setMode(m) {
    mode = m;
    // Re-emit from whichever side is now authoritative.
    if (m === "code") fromCode();
    else emit();
  }

  function setLevel(l) {
    level = l;
    if (advanced) pickedActions = [...LEVEL_ACTIONS[l]];
    fromBuilder();
  }
  function toggleBucket(b) {
    pickedBuckets = pickedBuckets.includes(b)
      ? pickedBuckets.filter((x) => x !== b)
      : [...pickedBuckets, b];
    fromBuilder();
  }
  function toggleSelectAll() {
    if (allFilteredPicked) {
      const drop = new Set(filteredBuckets);
      pickedBuckets = pickedBuckets.filter((b) => !drop.has(b));
    } else {
      const add = new Set([...pickedBuckets, ...filteredBuckets]);
      pickedBuckets = [...add];
    }
    fromBuilder();
  }
  function toggleAction(a) {
    pickedActions = pickedActions.includes(a)
      ? pickedActions.filter((x) => x !== a)
      : [...pickedActions, a];
    fromBuilder();
  }
  function setScope(s) {
    scope = s;
    fromBuilder();
  }
  function setAdvanced(on) {
    advanced = on;
    if (on && pickedActions.length === 0) pickedActions = [...LEVEL_ACTIONS[level]];
    fromBuilder();
  }
</script>

<div class="pb">
  <!-- View switch: plain buttons with aria-pressed (a toggle group, not a tab panel set). -->
  <div class="segmented" role="group" aria-label="Policy editor view">
    {#each [["builder", "Builder"], ["split", "Split"], ["code", "Code"]] as [m, label]}
      <button
        type="button"
        class="seg"
        class:active={mode === m}
        aria-pressed={mode === m}
        onclick={() => setMode(m)}>{label}</button>
    {/each}
  </div>

  <div class="pb-body" class:split={mode === "split"}>
    {#if mode !== "code"}
      <div class="pb-builder">
        {#if custom}
          <p class="notice warn" role="status">
            This policy isn't one the visual builder recognizes, so edit it as JSON in the Code view.
            Changing a control below will replace it.
          </p>
        {/if}

        <fieldset class="group">
          <legend class="label-sm">Which buckets</legend>
          <div class="seg-row" role="radiogroup" aria-label="Which buckets">
            <button
              type="button"
              class="chip"
              class:on={scope === "all"}
              role="radio"
              aria-checked={scope === "all"}
              onclick={() => setScope("all")}>All buckets</button>
            <button
              type="button"
              class="chip"
              class:on={scope === "specific"}
              role="radio"
              aria-checked={scope === "specific"}
              onclick={() => setScope("specific")}>Specific buckets</button>
          </div>

          {#if scope === "specific"}
            {#if bucketsLoading}
              <div class="bucket-pick is-status">
                <p class="muted" role="status">Loading buckets…</p>
              </div>
            {:else if buckets.length === 0}
              <p class="notice" role="status">
                There are no buckets yet. Create a bucket first, then come back to scope this user to
                it.
              </p>
            {:else}
              {#if buckets.length > 6}
                <div class="bucket-toolbar">
                  <input
                    type="search"
                    class="bucket-search"
                    placeholder="Filter buckets"
                    aria-label="Filter buckets"
                    bind:value={bucketFilter} />
                  <button
                    type="button"
                    class="btn small"
                    onclick={toggleSelectAll}
                    disabled={filteredBuckets.length === 0}>
                    {allFilteredPicked ? "Clear shown" : "Select shown"}
                  </button>
                </div>
              {/if}

              <div class="bucket-pick" role="group" aria-label="Buckets this user may use">
                {#if filteredBuckets.length === 0}
                  <p class="muted" style="margin:4px">No buckets match “{bucketFilter}”.</p>
                {:else}
                  {#each filteredBuckets as b (b)}
                    <label class="check">
                      <input
                        type="checkbox"
                        checked={pickedBuckets.includes(b)}
                        onchange={() => toggleBucket(b)} />
                      <span class="mono">{b}</span>
                    </label>
                  {/each}
                {/if}
              </div>

              {#if noBuckets}
                <p class="field-error" role="alert">
                  Pick at least one bucket, or switch to All buckets. With none selected this user
                  gets no access.
                </p>
              {:else}
                <p class="picked-count muted">
                  {pickedBuckets.length} selected.
                </p>
              {/if}
            {/if}
          {/if}
        </fieldset>

        <fieldset class="group">
          <legend class="label-sm">What they can do</legend>
          <label class="check toggle-adv">
            <input
              type="checkbox"
              checked={advanced}
              onchange={(e) => setAdvanced(e.target.checked)} />
            <span>Advanced: pick individual actions</span>
          </label>

          {#if !advanced}
            <div class="levels" role="radiogroup" aria-label="Permission level">
              {#each LEVELS as l (l.id)}
                <button
                  type="button"
                  class="level"
                  class:on={level === l.id}
                  role="radio"
                  aria-checked={level === l.id}
                  onclick={() => setLevel(l.id)}>
                  <strong>{l.label}</strong>
                  <span class="muted">{l.hint}</span>
                </button>
              {/each}
            </div>
          {:else}
            <div class="action-groups">
              {#each ACTION_GROUPS as g (g.label)}
                <div class="action-group">
                  <div class="label-sm">{g.label}</div>
                  {#each g.actions as a (a)}
                    <label class="check action-check">
                      <input
                        type="checkbox"
                        checked={pickedActions.includes(a)}
                        onchange={() => toggleAction(a)} />
                      <span class="action-text">
                        <span class="action-gloss">{ACTION_GLOSS[a] || a}</span>
                        <span class="mono action-verb">{a}</span>
                      </span>
                    </label>
                  {/each}
                </div>
              {/each}
            </div>
            {#if noActions}
              <p class="field-error" role="alert">
                Pick at least one action. With none selected this user gets no access.
              </p>
            {/if}
          {/if}
        </fieldset>

        <!-- Running, plain-language summary so the JSON is never the only thing explaining intent. -->
        {#if !custom}
          <div class="allow-summary" class:empty={builderGrantsNothing}>
            <div class="label-sm">This lets the user</div>
            {#if builderGrantsNothing}
              <p class="muted" style="margin:4px 0 0">
                Nothing yet. {noBuckets ? "Pick at least one bucket" : "Pick at least one action"} to
                grant access.
              </p>
            {:else}
              <ul>
                {#each allowPhrases as phrase (phrase)}
                  <li>{phrase}</li>
                {/each}
              </ul>
              <p class="scope-line muted">on {scopePhrase}.</p>
            {/if}
          </div>
        {/if}
      </div>
    {/if}

    {#if mode !== "builder"}
      <div class="pb-code">
        <label class="label-sm" for={`pb-json-${uid}`}>Policy JSON</label>
        <textarea
          id={`pb-json-${uid}`}
          class="policy-editor"
          class:invalid={!!error}
          aria-invalid={!!error}
          aria-describedby={error ? `pb-json-err-${uid}` : undefined}
          spellcheck="false"
          bind:value={rawText}
          oninput={fromCode}></textarea>
        {#if error}
          <p id={`pb-json-err-${uid}`} class="field-error" role="alert">{error}</p>
        {/if}
      </div>
    {/if}
  </div>
</div>

<style>
  .segmented {
    display: inline-flex;
    background: var(--surface-3);
    border-radius: var(--r-sm);
    padding: 3px;
    gap: 2px;
    margin-bottom: 12px;
  }
  .seg {
    border: none;
    background: transparent;
    color: var(--text-muted);
    padding: 6px 14px;
    border-radius: var(--r-sm);
    cursor: pointer;
    font-size: 0.85rem;
    font-weight: 500;
  }
  .seg.active {
    background: var(--surface);
    color: var(--text);
    box-shadow: var(--shadow-sm);
  }
  .pb-body.split {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 18px;
    align-items: start;
  }
  .pb-code textarea {
    width: 100%;
    min-height: 260px;
  }
  .group {
    border: none;
    padding: 0;
    margin: 0 0 16px;
    min-width: 0;
  }
  .group > legend {
    padding: 0;
    margin-bottom: 2px;
  }
  .seg-row {
    display: flex;
    gap: 8px;
    margin: 6px 0;
    flex-wrap: wrap;
  }
  .chip {
    border: 1px solid var(--border-strong);
    background: var(--surface);
    color: var(--text-muted);
    padding: 6px 12px;
    border-radius: 999px;
    cursor: pointer;
    font-size: 0.85rem;
  }
  .chip.on {
    border-color: var(--primary);
    background: var(--primary-tint);
    color: var(--primary-ink);
  }
  .bucket-toolbar {
    display: flex;
    gap: 8px;
    margin: 6px 0;
    align-items: center;
  }
  .bucket-search {
    flex: 1;
    min-width: 0;
  }
  .btn.small {
    padding: 5px 10px;
    font-size: 0.82rem;
    white-space: nowrap;
  }
  .bucket-pick {
    display: flex;
    flex-direction: column;
    gap: 4px;
    max-height: 170px;
    overflow: auto;
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 8px;
  }
  .bucket-pick.is-status {
    display: block;
  }
  .check {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.88rem;
    cursor: pointer;
    padding: 3px 2px;
  }
  .check input {
    flex-shrink: 0;
    width: 16px;
    height: 16px;
  }
  .toggle-adv {
    margin: 4px 0 10px;
  }
  .picked-count {
    margin: 6px 0 0;
    font-size: 0.82rem;
  }
  .levels {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .level {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    gap: 2px;
    text-align: left;
    border: 1px solid var(--border-strong);
    background: var(--surface);
    border-radius: var(--r);
    padding: 10px 14px;
    cursor: pointer;
  }
  .level.on {
    border-color: var(--primary);
    background: var(--primary-tint);
  }
  .level .muted {
    font-size: 0.8rem;
  }
  .action-groups {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px 18px;
  }
  .action-check {
    align-items: flex-start;
    padding: 4px 2px;
  }
  .action-text {
    display: flex;
    flex-direction: column;
    gap: 1px;
    line-height: 1.3;
  }
  .action-gloss {
    font-size: 0.86rem;
    color: var(--text);
  }
  .action-verb {
    font-size: 0.74rem;
    color: var(--text-faint);
  }
  .allow-summary {
    margin-top: 4px;
    background: var(--primary-tint);
    border-radius: var(--r);
    padding: 12px 14px;
  }
  .allow-summary.empty {
    background: var(--surface-2);
    border: 1px solid var(--border);
  }
  .allow-summary ul {
    margin: 6px 0 0;
    padding-left: 18px;
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .allow-summary li {
    font-size: 0.88rem;
    color: var(--text);
  }
  .allow-summary .scope-line {
    margin: 7px 0 0;
    font-size: 0.84rem;
  }
  @media (max-width: 720px) {
    .pb-body.split {
      grid-template-columns: 1fr;
    }
    .action-groups {
      grid-template-columns: 1fr;
    }
  }
</style>
