// web/src/views/buckets.tsx
import { useEffect, useId, useState, type FormEvent } from "react";
import { useNavigate, useSearchParams } from "react-router";
import { Database, MoreHorizontal, Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/primitives/button";
import { Checkbox } from "@/components/primitives/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/primitives/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/primitives/dropdown-menu";
import { Input } from "@/components/primitives/input";
import { Label } from "@/components/primitives/label";
import { TableCell, TableRow } from "@/components/primitives/table";
import { BulkBar } from "@/components/bulk-bar";
import { DataTable, SkeletonRows, type Column } from "@/components/data-table";
import { EmptyState } from "@/components/empty-state";
import { useBulkSelection } from "@/hooks/use-bulk-selection";
import { ErrorAlert } from "@/components/error-alert";
import { FieldError } from "@/components/field-error";
import { Page, PageHeader } from "@/components/page-header";
import { StatusBadge, type StatusTone } from "@/components/status-badge";
import { TextLink } from "@/components/text-link";
import { TypedConfirmDialog } from "@/components/typed-confirm-dialog";
import { api, ApiError, errorMessage } from "@/lib/api";
import { bytes, count, whenMs } from "@/lib/format";
import { useResource } from "@/lib/use-resource";
import { useLiveTopic } from "@/lib/live";

const NAME_RULE =
  "3–63 characters: lowercase letters, digits, hyphens, and dots; must start and end with a letter or digit.";

/** S3-style bucket-name check; returns a specific problem or null when valid. */
function nameIssue(name: string): string | null {
  if (name.length < 3 || name.length > 63)
    return "Bucket names must be 3–63 characters long.";
  if (!/^[a-z0-9.-]+$/.test(name))
    return "Only lowercase letters, digits, hyphens, and dots are allowed.";
  if (!/^[a-z0-9]/.test(name) || !/[a-z0-9]$/.test(name))
    return "Names must start and end with a letter or digit.";
  return null;
}

const COLUMNS: Column[] = [
  { key: "name", label: "Name" },
  { key: "objects", label: "Objects", className: "text-right" },
  { key: "size", label: "Size", className: "text-right" },
  { key: "versioning", label: "Versioning" },
  { key: "created", label: "Created" },
  { key: "actions", label: "Actions", srOnly: true },
];

/** Map a bucket's versioning state to a semantic badge tone. */
function versioningTone(state: string): StatusTone {
  if (state === "Enabled") return "positive";
  if (state === "Suspended") return "warning";
  return "neutral";
}

export function Buckets() {
  const navigate = useNavigate();
  // The list plus per-bucket usage (objects + bytes) in one refreshable unit;
  // usage failing alone degrades to em-dashes rather than failing the page.
  const list = useResource(async () => {
    const [l, usage] = await Promise.all([
      api.listBuckets(),
      api.overviewBuckets().catch(() => null),
    ]);
    return {
      buckets: l.buckets,
      usage: new Map((usage?.buckets ?? []).map((u) => [u.name, u])),
    };
  }, []);
  const buckets = list.data?.buckets ?? [];
  // Live: the server pushes a "buckets" usage snapshot on a cadence; refresh through the list fetch.
  useLiveTopic("buckets", list.refresh);

  // ---- bulk selection ------------------------------------------------------
  const sel = useBulkSelection();
  const allIds = buckets.map((b) => b.name);
  const allSelected = allIds.length > 0 && allIds.every((id) => sel.has(id));
  const someSelected = sel.count > 0 && !allSelected;
  const [bulkDeleting, setBulkDeleting] = useState(false);
  const [confirmBulk, setConfirmBulk] = useState(false);

  // The leading select column carries a header "select all" checkbox; the rest
  // are the static data columns.
  const columns: Column[] = [
    {
      key: "select",
      className: "w-10",
      label: (
        <Checkbox
          checked={allSelected ? true : someSelected ? "indeterminate" : false}
          onCheckedChange={(v) => sel.setAll(allIds, v === true)}
          aria-label="Select all buckets"
        />
      ),
    },
    ...COLUMNS,
  ];

  async function confirmBulkDelete() {
    if (sel.count === 0 || bulkDeleting) return;
    setBulkDeleting(true);
    const targets = [...sel.selected];
    let ok = 0;
    const failed: string[] = [];
    for (const t of targets) {
      try {
        await api.deleteBucket(t);
        ok++;
      } catch {
        failed.push(t);
      }
    }
    if (failed.length === 0) {
      toast.success(`Deleted ${ok} bucket${ok === 1 ? "" : "s"}.`);
    } else {
      toast.error(
        `Deleted ${ok}, ${failed.length} failed (${failed.join(", ")}). Buckets must be empty or you must own them.`,
      );
    }
    sel.clear();
    setConfirmBulk(false);
    setBulkDeleting(false);
    list.refresh();
  }

  // ---- create dialog -------------------------------------------------------
  const nameId = useId();
  const helpId = useId();
  const errId = useId();
  const [createOpen, setCreateOpen] = useState(false);
  const [name, setName] = useState("");
  const [objectLock, setObjectLock] = useState(false);
  const [creating, setCreating] = useState(false);
  // Server-side failure (409 duplicate, etc.) shown on the name field.
  const [serverError, setServerError] = useState<string | null>(null);

  const clientIssue = name ? nameIssue(name) : null;
  const fieldError = serverError ?? clientIssue;
  const canCreate = !!name && !clientIssue && !creating;

  function openCreate(open: boolean) {
    setCreateOpen(open);
    if (open) {
      setName("");
      setObjectLock(false);
      setServerError(null);
    }
  }

  // The command palette's "Create bucket" action lands here with ?new=1 — open the create dialog and
  // strip the param so a refresh or Back doesn't reopen it.
  const [searchParams, setSearchParams] = useSearchParams();
  useEffect(() => {
    if (searchParams.get("new") !== "1") return;
    openCreate(true);
    const next = new URLSearchParams(searchParams);
    next.delete("new");
    setSearchParams(next, { replace: true });
  }, [searchParams, setSearchParams]);

  async function create(e: FormEvent) {
    e.preventDefault();
    if (!canCreate) return;
    setCreating(true);
    setServerError(null);
    try {
      await api.createBucket(name, objectLock);
      toast.success(`Bucket "${name}" created.`);
      setCreateOpen(false);
      list.refresh();
    } catch (err) {
      if (err instanceof ApiError && err.status === 409) {
        setServerError(`A bucket named "${name}" already exists.`);
      } else {
        setServerError(errorMessage(err, "Failed to create bucket."));
      }
    } finally {
      setCreating(false);
    }
  }

  // ---- delete flow ---------------------------------------------------------
  const [pendingDelete, setPendingDelete] = useState<string | null>(null);
  const [deleting, setDeleting] = useState(false);

  async function confirmDelete() {
    const target = pendingDelete;
    if (!target || deleting) return;
    setDeleting(true);
    try {
      await api.deleteBucket(target);
      toast.success(`Bucket "${target}" deleted.`);
      setPendingDelete(null);
      list.refresh();
    } catch (err) {
      toast.error(errorMessage(err, "Failed to delete bucket."));
    } finally {
      setDeleting(false);
    }
  }

  const createButton = (
    <Button onClick={() => openCreate(true)}>
      <Plus aria-hidden="true" /> Create bucket
    </Button>
  );

  return (
    <Page>
      <PageHeader
        title="Buckets"
        description="Top-level containers for your objects."
        actions={createButton}
      />

      {list.error ? (
        <ErrorAlert
          title="Couldn't load buckets"
          message={list.error}
          onRetry={list.refresh}
        />
      ) : null}

      {list.loading ? (
        <DataTable columns={columns} minWidth={760}>
          <SkeletonRows
            rows={3}
            widths={["w-4", "w-32", "w-10", "w-16", "w-20", "w-36", "w-8"]}
          />
        </DataTable>
      ) : buckets.length === 0 && !list.error ? (
        <EmptyState
          icon={Database}
          title="No buckets yet"
          body="A bucket is a top-level container that holds your files as objects."
          action={createButton}
        />
      ) : (
        <>
          <BulkBar count={sel.count} onClear={sel.clear}>
            <Button
              variant="destructive-outline"
              size="sm"
              disabled={bulkDeleting}
              onClick={() => setConfirmBulk(true)}
            >
              Delete selected
            </Button>
          </BulkBar>
          <DataTable columns={columns} minWidth={760}>
            {buckets.map((b) => (
              <TableRow
                key={b.name}
                data-state={sel.has(b.name) ? "selected" : undefined}
              >
                <TableCell>
                  <Checkbox
                    checked={sel.has(b.name)}
                    onCheckedChange={() => sel.toggle(b.name)}
                    aria-label={`Select ${b.name}`}
                  />
                </TableCell>
                <TableCell>
                  <TextLink
                    to={`/buckets/${encodeURIComponent(b.name)}/browser`}
                    className="font-mono text-[13px]"
                  >
                    {b.name}
                  </TextLink>
                </TableCell>
              <TableCell
                data-label="Objects"
                className="text-right text-[13px] tabular-nums"
              >
                {count(list.data?.usage.get(b.name)?.objects ?? null)}
              </TableCell>
              <TableCell
                data-label="Size"
                className="text-right text-[13px] tabular-nums"
              >
                {bytes(list.data?.usage.get(b.name)?.logical_bytes ?? null)}
              </TableCell>
              <TableCell data-label="Versioning">
                <StatusBadge tone={versioningTone(b.versioning)}>
                  {b.versioning}
                </StatusBadge>
              </TableCell>
              <TableCell
                data-label="Created"
                className="text-[13px] text-muted-foreground tabular-nums"
              >
                {whenMs(b.created_at_ms)}
              </TableCell>
              <TableCell className="text-right">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      aria-label={`Actions for ${b.name}`}
                    >
                      <MoreHorizontal aria-hidden="true" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem
                      onSelect={() =>
                        navigate(`/buckets/${encodeURIComponent(b.name)}/browser`)
                      }
                    >
                      Browse
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      onSelect={() =>
                        navigate(`/buckets/${encodeURIComponent(b.name)}/settings`)
                      }
                    >
                      Settings
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem
                      variant="destructive"
                      onSelect={() => setPendingDelete(b.name)}
                    >
                      Delete
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          ))}
          </DataTable>
        </>
      )}

      <Dialog open={createOpen} onOpenChange={creating ? undefined : openCreate}>
        <DialogContent className="sm:max-w-md">
          <form onSubmit={create} noValidate>
            <DialogHeader>
              <DialogTitle>Create bucket</DialogTitle>
              <DialogDescription>
                Bucket names are permanent — they can&apos;t be renamed later.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-1.5 py-4">
              <Label htmlFor={nameId}>Bucket name</Label>
              <Input
                id={nameId}
                value={name}
                placeholder="photos"
                autoComplete="off"
                spellCheck={false}
                className="font-mono"
                aria-invalid={fieldError ? true : undefined}
                aria-describedby={fieldError ? `${helpId} ${errId}` : helpId}
                onChange={(e) => {
                  setName(e.target.value);
                  setServerError(null);
                }}
              />
              <p id={helpId} className="text-[13px] text-muted-foreground">
                {NAME_RULE}
              </p>
              <div id={errId}>
                <FieldError>{fieldError}</FieldError>
              </div>

              <label className="mt-2 flex items-start gap-2 rounded-md border p-3 text-sm">
                <Checkbox
                  checked={objectLock}
                  disabled={creating}
                  onCheckedChange={(v) => setObjectLock(v === true)}
                  className="mt-0.5"
                />
                <span>
                  Enable Object Lock (WORM)
                  <span className="mt-0.5 block text-[13px] font-normal text-muted-foreground">
                    Forces versioning on and lets you set retention &amp; legal
                    holds. This can only be enabled now, not later.
                  </span>
                </span>
              </label>
            </div>
            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                disabled={creating}
                onClick={() => setCreateOpen(false)}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={!canCreate}>
                {creating ? "Creating…" : "Create bucket"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      <TypedConfirmDialog
        open={pendingDelete !== null}
        onOpenChange={(open) => {
          if (!open) setPendingDelete(null);
        }}
        title="Delete bucket"
        description={((n) =>
          n && n > 0
            ? `This bucket holds ${n.toLocaleString()} object${n === 1 ? "" : "s"} — deleting it permanently removes the bucket and every object and version in it, not just the bucket. This can't be undone.`
            : "This permanently deletes the bucket and every object and version in it. This can't be undone.")(
          pendingDelete ? (list.data?.usage.get(pendingDelete)?.objects ?? null) : null,
        )}
        requireText={pendingDelete ?? ""}
        confirmLabel={deleting ? "Deleting…" : "Delete bucket"}
        cancelLabel="Keep bucket"
        busy={deleting}
        onConfirm={() => void confirmDelete()}
      />

      <TypedConfirmDialog
        open={confirmBulk}
        onOpenChange={(open) => {
          if (!open && !bulkDeleting) setConfirmBulk(false);
        }}
        title={`Delete ${sel.count} bucket${sel.count === 1 ? "" : "s"}`}
        description={`This permanently deletes ${sel.count} bucket${sel.count === 1 ? "" : "s"} and every object and version inside them. This cannot be undone.`}
        requireText={`delete ${sel.count} bucket${sel.count === 1 ? "" : "s"}`}
        confirmLabel={bulkDeleting ? "Deleting…" : "Delete selected"}
        cancelLabel="Keep buckets"
        busy={bulkDeleting}
        onConfirm={() => void confirmBulkDelete()}
      />
    </Page>
  );
}

// ui/src/views/Buckets.svelte
<script>
  import { api, ApiError } from "../lib/api.js";
  import { whenMs } from "../lib/format.js";
  import { navigate } from "../lib/router.js";
  import { ok, err } from "../lib/toast.js";
  import ConfirmDialog from "../components/ConfirmDialog.svelte";
  import Skeleton from "../components/Skeleton.svelte";

  let buckets = $state([]);
  let error = $state("");
  let loading = $state(true);

  let newName = $state("");
  let nameError = $state("");
  let creating = $state(false);

  // Delete confirmation is driven by a typed-name gate, not a native confirm().
  let pendingDelete = $state(null); // bucket name awaiting confirmation, or null
  let deleting = $state(false);

  async function load() {
    loading = true;
    error = "";
    try {
      const res = await api.listBuckets();
      buckets = (res && res.buckets) || [];
    } catch (e) {
      error = e.message || "Failed to load buckets.";
    } finally {
      loading = false;
    }
  }

  async function create(e) {
    e.preventDefault();
    nameError = "";
    const name = newName.trim();
    if (!name) {
      nameError = "Enter a name for the new bucket.";
      return;
    }
    creating = true;
    try {
      await api.createBucket(name);
      ok(`Bucket "${name}" created.`);
      newName = "";
      await load();
    } catch (e) {
      if (e instanceof ApiError && e.status === 409) {
        nameError = `A bucket named "${name}" already exists.`;
      } else {
        nameError = e.message || "Failed to create bucket.";
      }
    } finally {
      creating = false;
    }
  }

  function askDelete(name) {
    pendingDelete = name;
  }

  async function confirmDelete() {
    const name = pendingDelete;
    if (!name) return;
    deleting = true;
    try {
      await api.deleteBucket(name);
      ok(`Bucket "${name}" deleted.`);
      pendingDelete = null;
      await load();
    } catch (e) {
      err(e.message || "Failed to delete bucket.");
    } finally {
      deleting = false;
    }
  }

  load();
</script>

<h1>Buckets</h1>
<p class="subtitle">List, create, inspect, and remove buckets.</p>

{#if error}
  <div class="notice danger" role="alert">{error}</div>
{/if}

<div class="panel">
  <form class="create-row" onsubmit={create}>
    <div class="field create-field">
      <label class="label" for="new-bucket-name">New bucket name</label>
      <input
        id="new-bucket-name"
        placeholder="photos"
        bind:value={newName}
        oninput={() => (nameError = "")}
        aria-invalid={nameError ? "true" : undefined}
        aria-describedby={nameError ? "new-bucket-error" : undefined}
        autocomplete="off"
      />
      {#if nameError}
        <span id="new-bucket-error" class="field-error" role="alert">{nameError}</span>
      {/if}
    </div>
    <button class="primary" type="submit" disabled={creating}>
      {creating ? "Creating…" : "Create bucket"}
    </button>
  </form>
</div>

{#if loading}
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Owner</th>
          <th>Versioning</th>
          <th>Created</th>
          <th><span class="visually-hidden">Actions</span></th>
        </tr>
      </thead>
      <tbody>
        {#each Array(3) as _, i (i)}
          <tr>
            <td colspan="5"><Skeleton lines={1} /></td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{:else if buckets.length === 0}
  <div class="empty">
    <p class="empty-title">No buckets yet</p>
    <p class="empty-body">
      A bucket is a top-level container for your files. Name one above to get started,
      then open it to upload objects.
    </p>
  </div>
{:else}
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Owner</th>
          <th>Versioning</th>
          <th>Created</th>
          <th><span class="visually-hidden">Actions</span></th>
        </tr>
      </thead>
      <tbody>
        {#each buckets as b (b.name)}
          <tr>
            <td class="mono">
              <a
                href={`#/buckets/${encodeURIComponent(b.name)}/browser`}
                onclick={(e) => {
                  e.preventDefault();
                  navigate(`/buckets/${encodeURIComponent(b.name)}/browser`);
                }}>{b.name}</a
              >
            </td>
            <td class="mono">{b.owner_id || "—"}</td>
            <td><span class="badge">{b.versioning}</span></td>
            <td>{whenMs(b.created_at_ms)}</td>
            <td class="row-actions">
              <button class="danger sm" onclick={() => askDelete(b.name)}>
                Delete
              </button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}

<ConfirmDialog
  open={pendingDelete !== null}
  danger
  title="Delete bucket"
  body="This permanently deletes the bucket and everything in it. Type the name to confirm."
  confirmLabel={deleting ? "Deleting…" : "Delete bucket"}
  cancelLabel="Keep bucket"
  requireText={pendingDelete}
  onconfirm={confirmDelete}
  oncancel={() => (pendingDelete = null)}
/>

<style>
  .create-row {
    display: flex;
    align-items: flex-end;
    gap: 12px;
    flex-wrap: wrap;
  }
  .create-field {
    flex: 1 1 220px;
    margin-bottom: 0;
    min-width: 0;
  }
  .create-row > button {
    flex-shrink: 0;
  }
  .row-actions {
    text-align: right;
    white-space: nowrap;
  }
  .empty-title {
    font-size: 1.05rem;
    font-weight: 600;
    color: var(--text);
    margin: 0 0 6px;
  }
  .empty-body {
    margin: 0 auto;
    max-width: 38ch;
    line-height: 1.55;
  }
</style>
