// web/src/views/overview.tsx
// Overview: node-wide storage and compression at a glance, plus per-bucket
// usage. One combined load (overview + per-bucket usage + system facts) so
// the page arrives as a whole; Refresh re-fetches without tearing it down.

import { useMemo } from "react";
import { useNavigate } from "react-router";
import { Database } from "lucide-react";
import { api } from "@/lib/api";
import { actionLabel, isDestructiveAction } from "@/lib/activity";
import { bytes, count, duration, ratio, relTime, whenMs } from "@/lib/format";
import { cn } from "@/lib/utils";
import { useResource } from "@/lib/use-resource";
import { useLiveTopic } from "@/lib/live";
import { EmptyState } from "@/components/empty-state";
import { ErrorAlert } from "@/components/error-alert";
import { Page, PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { StatusBadge } from "@/components/status-badge";
import { TextLink } from "@/components/text-link";
import { UsageBar } from "@/components/usage-bar";
import { Button } from "@/components/primitives/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/primitives/card";
import { Skeleton } from "@/components/primitives/skeleton";

export function Overview() {
  const navigate = useNavigate();

  const { data, error, loading, refresh } = useResource(
    () =>
      Promise.all([
        api.overview(),
        api.overviewBuckets(),
        api.system(),
        // The activity teaser is decoration — its failure never fails the page.
        api.activity(6).catch(() => null),
      ]).then(([overview, perBucket, system, activity]) => ({
        overview,
        perBucket: perBucket.buckets,
        system,
        activity: activity?.entries ?? [],
      })),
    [],
  );
  // Live: the server pushes an "overview" snapshot on a cadence; flow it through the normal fetch.
  useLiveTopic("overview", refresh);

  const buckets = useMemo(
    () =>
      [...(data?.perBucket ?? [])].sort(
        (a, b) => b.logical_bytes - a.logical_bytes,
      ),
    [data],
  );
  const totalLogical = useMemo(
    () => buckets.reduce((sum, b) => sum + b.logical_bytes, 0),
    [buckets],
  );

  const o = data?.overview;
  const sys = data?.system;

  // Compression figures. `saved` is clamped at zero: when data didn't
  // compress (physical > logical) we say so in plain words instead of
  // rendering a negative bar.
  const logical = o?.logical_bytes ?? 0;
  const physical = o?.physical_bytes ?? 0;
  const saved = Math.max(0, logical - physical);
  const savedPct = logical > 0 ? Math.round((saved / logical) * 100) : 0;
  const compressed = logical > 0 && physical <= logical;

  return (
    <Page>
      <PageHeader
        title="Overview"
        description="Storage, compression, and per-bucket usage across this node."
      />

      {error ? (
        <ErrorAlert
          title="Could not load the overview"
          message={error}
          onRetry={refresh}
        />
      ) : null}

      {loading ? (
        <OverviewSkeleton />
      ) : data && o && sys ? (
        <div className="space-y-4">
          {/* Stat grid: the four numbers the eye should land on first. */}
          <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
            <StatCard label="Buckets" value={count(o.buckets)} />
            <StatCard label="Objects" value={count(o.objects)} />
            <StatCard label="Versions" value={count(o.versions)} />
            <StatCard
              label="Stored"
              value={bytes(o.physical_bytes)}
              sub={`of ${bytes(o.logical_bytes)} original`}
            />
          </div>

          {/* items-start so each card sizes to its own content — the Compression card is much
              shorter than Node, and stretching it to match left a large empty void. */}
          <div className="grid items-start gap-4 lg:grid-cols-2">
            {/* Node card: identity and health facts for this instance. */}
            <Card className="gap-4">
              <CardHeader className="gap-1">
                <CardTitle>Node</CardTitle>
                <CardDescription>This Cairn instance.</CardDescription>
              </CardHeader>
              <CardContent>
                <dl className="space-y-3 text-sm">
                  <div className="flex items-baseline justify-between gap-4">
                    <dt className="shrink-0 text-muted-foreground">Version</dt>
                    {/* The version already carries its own form — `vYYYY.MM.DD` for a release,
                        `x.y.z-dev+gSHA` for a dev build — so render it verbatim (no prepended `v`). */}
                    <dd className="font-mono text-[13px]">{sys.version}</dd>
                  </div>
                  <div className="flex items-baseline justify-between gap-4">
                    <dt className="shrink-0 text-muted-foreground">Uptime</dt>
                    <dd className="text-[13px]">
                      {duration(sys.uptime_secs)}
                    </dd>
                  </div>
                  <div className="flex items-baseline justify-between gap-4">
                    <dt className="shrink-0 text-muted-foreground">S3 API</dt>
                    <dd className="min-w-0 truncate font-mono text-[13px]">
                      {sys.s3_addr}
                    </dd>
                  </div>
                  <div className="flex items-baseline justify-between gap-4">
                    <dt className="shrink-0 text-muted-foreground">Console</dt>
                    <dd className="min-w-0 text-right">
                      <span className="block truncate font-mono text-[13px]">
                        {sys.web_addr}
                      </span>
                      <span className="block text-xs text-muted-foreground">
                        configured address
                      </span>
                    </dd>
                  </div>
                  <div className="flex items-baseline justify-between gap-4">
                    <dt className="shrink-0 text-muted-foreground">TLS</dt>
                    <dd>
                      <StatusBadge tone={sys.tls ? "positive" : "neutral"}>
                        {sys.tls ? "TLS on" : "TLS off"}
                      </StatusBadge>
                    </dd>
                  </div>
                  <div className="flex items-baseline justify-between gap-4">
                    <dt className="shrink-0 text-muted-foreground">
                      Data directory
                    </dt>
                    <dd
                      className="min-w-0 truncate font-mono text-[13px]"
                      title={sys.data_dir}
                    >
                      {sys.data_dir}
                    </dd>
                  </div>
                </dl>

                {sys.disk_total_bytes != null &&
                sys.disk_free_bytes != null ? (
                  <div className="mt-5 space-y-1.5">
                    <p className="text-sm text-muted-foreground">Disk</p>
                    {(() => {
                      const usedPct =
                        ((sys.disk_total_bytes - sys.disk_free_bytes) /
                          sys.disk_total_bytes) *
                        100;
                      return (
                        <UsageBar
                          percent={usedPct}
                          // A near-full disk is exactly when an operator wants a signal.
                          fillClassName={cn(
                            usedPct >= 95
                              ? "bg-destructive"
                              : usedPct >= 85
                                ? "bg-warning"
                                : undefined,
                          )}
                          label={`Disk: ${bytes(
                            sys.disk_total_bytes - sys.disk_free_bytes,
                          )} used of ${bytes(sys.disk_total_bytes)}`}
                        />
                      );
                    })()}
                    <p className="text-xs text-muted-foreground">
                      {bytes(sys.disk_free_bytes)} free of{" "}
                      {bytes(sys.disk_total_bytes)}
                    </p>
                  </div>
                ) : (
                  <p className="mt-5 text-sm text-muted-foreground">
                    Disk usage unavailable.
                  </p>
                )}
              </CardContent>
            </Card>

            {/* Compression card: how much disk space compression saves. Leads with the ratio (the
                number that matters), and the bar fills to the SAVED proportion — so a high ratio
                reads as a full bar, not the near-empty 'stored' bar that contradicted the headline. */}
            <Card className="gap-4">
              <CardHeader className="gap-1">
                <CardTitle>Compression</CardTitle>
                <CardDescription>
                  How much disk space compression saves.
                </CardDescription>
              </CardHeader>
              <CardContent>
                {logical === 0 ? (
                  <p className="text-sm text-muted-foreground">
                    No data to compress yet — upload objects to a bucket to see
                    the space compression saves.
                  </p>
                ) : compressed ? (
                  <div className="space-y-4">
                    <div className="flex items-baseline gap-2">
                      <span className="text-3xl font-semibold tracking-tight tabular-nums">
                        {ratio(o.compression_ratio)}
                      </span>
                      <span className="text-sm text-muted-foreground">
                        smaller — {savedPct}% saved
                      </span>
                    </div>
                    <UsageBar
                      percent={savedPct}
                      label={`${savedPct}% saved: ${bytes(saved)} of ${bytes(
                        logical,
                      )} original`}
                    />
                    <dl className="space-y-2 text-sm">
                      <div className="flex items-baseline justify-between gap-4">
                        <dt className="text-muted-foreground">Stored</dt>
                        <dd className="font-mono text-[13px]">
                          {bytes(physical)}
                        </dd>
                      </div>
                      <div className="flex items-baseline justify-between gap-4">
                        <dt className="text-muted-foreground">Saved</dt>
                        <dd className="font-mono text-[13px]">
                          {bytes(saved)}
                        </dd>
                      </div>
                      <div className="flex items-baseline justify-between gap-4">
                        <dt className="text-muted-foreground">Original</dt>
                        <dd className="font-mono text-[13px]">
                          {bytes(logical)}
                        </dd>
                      </div>
                    </dl>
                  </div>
                ) : (
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    This data didn&apos;t compress (stored {bytes(physical)} vs{" "}
                    {bytes(logical)} original).
                  </p>
                )}
              </CardContent>
            </Card>
          </div>

          {/* Per-bucket usage: each bucket's share of total original bytes. */}
          <Card className="gap-4">
            <CardHeader className="gap-1">
              <CardTitle>Storage by bucket</CardTitle>
              <CardDescription>
                Each bucket&apos;s share of total original bytes.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {buckets.length === 0 ? (
                <EmptyState
                  icon={Database}
                  title="No buckets yet"
                  body="Create your first bucket to see usage here."
                  action={
                    <Button
                      variant="outline"
                      onClick={() => navigate("/buckets")}
                    >
                      Go to buckets
                    </Button>
                  }
                />
              ) : (
                <ul className="space-y-3">
                  {buckets.slice(0, 8).map((b) => {
                    const pct = Math.round(
                      (b.logical_bytes / Math.max(1, totalLogical)) * 100,
                    );
                    return (
                      <li
                        key={b.name}
                        className="grid grid-cols-[1fr_auto] items-center gap-x-4 gap-y-2 sm:grid-cols-[minmax(0,11rem)_1fr_auto]"
                      >
                        <TextLink
                          to={`/buckets/${encodeURIComponent(b.name)}/browser`}
                          className="min-w-0 truncate font-mono text-[13px]"
                          title={b.name}
                        >
                          {b.name}
                        </TextLink>
                        {/* On mobile the bar drops to its own full-width row
                            below the name + bytes; at sm: it sits inline as the
                            middle column of the 3-column grid. */}
                        <div className="order-last col-span-2 sm:order-none sm:col-span-1">
                          <UsageBar
                            percent={pct}
                            label={`${b.name}: ${bytes(
                              b.logical_bytes,
                            )}, ${pct}% of total storage`}
                          />
                        </div>
                        <div className="text-right">
                          <p className="font-mono text-[13px]">
                            {bytes(b.logical_bytes)}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {count(b.objects)} {b.objects === 1 ? "object" : "objects"}
                          </p>
                        </div>
                      </li>
                    );
                  })}
                  {buckets.length > 8 ? (
                    <li className="pt-1">
                      <TextLink to="/buckets" className="text-[13px]">
                        and {count(buckets.length - 8)} more →
                      </TextLink>
                    </li>
                  ) : null}
                </ul>
              )}
            </CardContent>
          </Card>

          {/* Recent activity teaser: the latest administrative changes, with
              the full log one click away. */}
          {data && data.activity.length > 0 ? (
            <Card className="gap-3">
              <CardHeader className="gap-1">
                <CardTitle>Recent activity</CardTitle>
                <CardDescription>
                  The latest administrative changes on this node.
                </CardDescription>
                <CardAction>
                  <TextLink to="/activity" className="text-[13px]">
                    View all
                  </TextLink>
                </CardAction>
              </CardHeader>
              <CardContent>
                <ul className="divide-y">
                  {data.activity.map((e, i) => (
                    <li
                      key={`${e.at_ms}:${e.action}:${i}`}
                      className="flex flex-wrap items-baseline gap-x-3 gap-y-0.5 py-2 first:pt-0 last:pb-0"
                    >
                      <span
                        className={cn(
                          "text-sm font-medium",
                          isDestructiveAction(e.action) && "text-destructive",
                        )}
                        title={e.action}
                      >
                        {actionLabel(e.action)}
                      </span>
                      {e.bucket ? (
                        <TextLink
                          to={`/buckets/${encodeURIComponent(e.bucket)}/browser`}
                          className="font-mono text-[13px]"
                        >
                          {e.bucket}
                        </TextLink>
                      ) : null}
                      {e.key ? (
                        <span
                          className="max-w-[24ch] truncate font-mono text-[13px] text-muted-foreground"
                          title={e.key}
                        >
                          {e.key}
                        </span>
                      ) : null}
                      <span
                        className="ms-auto text-[13px] text-muted-foreground tabular-nums"
                        title={whenMs(e.at_ms)}
                      >
                        {relTime(e.at_ms)}
                      </span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ) : null}
        </div>
      ) : null}
    </Page>
  );
}

/** First-paint skeletons mirroring the real layout so nothing jumps. */
function OverviewSkeleton() {
  return (
    <div className="space-y-4">
      <p className="sr-only" role="status">
        Loading overview…
      </p>
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4" aria-hidden="true">
        <StatCard label="Buckets" value="" loading />
        <StatCard label="Objects" value="" loading />
        <StatCard label="Versions" value="" loading />
        <StatCard label="Stored" value="" sub=" " loading />
      </div>
      <div className="grid gap-4 lg:grid-cols-2" aria-hidden="true">
        <Skeleton className="h-72 rounded-lg" />
        <Skeleton className="h-72 rounded-lg" />
      </div>
      <Skeleton className="h-44 rounded-lg" aria-hidden="true" />
    </div>
  );
}

// ui/src/views/Overview.svelte
<script>
  import { api } from "../lib/api.js";
  import { bytes, count, ratio } from "../lib/format.js";
  import { navigate } from "../lib/router.js";
  import Skeleton from "../components/Skeleton.svelte";

  let data = $state(null);
  let buckets = $state([]);
  let error = $state("");
  // `loading` is the first paint (no data yet). `refreshing` is a re-fetch while
  // data is still on screen, so we never tear the page down on Refresh.
  let loading = $state(true);
  let refreshing = $state(false);

  async function load() {
    if (data) refreshing = true;
    else loading = true;
    error = "";
    try {
      const next = await api.overview();
      const list = await api.listBuckets();
      const names = (list?.buckets || []).map((b) => b.name);
      const details = await Promise.all(
        names.map(async (n) => {
          try {
            const d = await api.getBucket(n);
            return { name: n, objects: d.object_count, size: d.logical_bytes };
          } catch {
            return { name: n, objects: 0, size: 0 };
          }
        }),
      );
      details.sort((a, b) => b.size - a.size);
      data = next;
      buckets = details;
    } catch (err) {
      error = err.message || "Failed to load overview.";
    } finally {
      loading = false;
      refreshing = false;
    }
  }
  load();

  const maxSize = $derived(Math.max(1, ...buckets.map((b) => b.size)));
  const saved = $derived(
    data ? Math.max(0, data.logical_bytes - data.physical_bytes) : 0,
  );
  // Stored fraction of original (0..1), for the compression bar.
  const storedFrac = $derived(
    data && data.logical_bytes > 0
      ? Math.min(1, data.physical_bytes / data.logical_bytes)
      : 1,
  );
  const storedPct = $derived(Math.round(storedFrac * 100));
  const savedPct = $derived(
    data && data.logical_bytes > 0
      ? Math.round((saved / data.logical_bytes) * 100)
      : 0,
  );

  function bucketSharePct(size) {
    return Math.round((size / maxSize) * 100);
  }
</script>

<h1>Overview</h1>
<p class="subtitle">Storage, compression, and per-bucket usage across the node.</p>

{#if error}
  <div class="notice danger" role="alert">{error}</div>
{/if}

{#if loading}
  <!-- First paint: skeletons that mirror the real layout so nothing jumps. -->
  <div class="tier tier-primary" aria-hidden="true">
    <div class="card stat stat-lead"><Skeleton lines={2} /></div>
    <div class="card stat stat-lead"><Skeleton lines={2} /></div>
    <div class="card stat stat-lead"><Skeleton lines={2} /></div>
  </div>
  <div class="tier tier-storage" aria-hidden="true">
    <div class="card stat"><Skeleton lines={2} /></div>
    <div class="card stat"><Skeleton lines={2} /></div>
  </div>
  <div class="panel" aria-hidden="true">
    <Skeleton lines={1} width="40%" />
    <div class="skel-bar"><Skeleton block height="14px" /></div>
    <Skeleton lines={2} />
  </div>
  <span class="visually-hidden" role="status">Loading overview…</span>
{:else if data}
  <!-- Primary tier: the three counts the eye should land on first. -->
  <div class="tier tier-primary">
    <div class="card stat stat-lead">
      <div class="label">Buckets</div>
      <div class="value">{count(data.buckets)}</div>
    </div>
    <div class="card stat stat-lead">
      <div class="label">Objects</div>
      <div class="value">{count(data.objects)}</div>
    </div>
    <div class="card stat stat-lead">
      <div class="label">Versions</div>
      <div class="value">{count(data.versions)}</div>
    </div>
  </div>

  <!-- Storage tier: the two size figures, with a plain-language gloss. -->
  <div class="tier tier-storage">
    <div class="card stat">
      <div class="label">Original size</div>
      <div class="value mono">{bytes(data.logical_bytes)}</div>
      <p class="stat-gloss">What you uploaded.</p>
    </div>
    <div class="card stat">
      <div class="label">Stored size</div>
      <div class="value mono">{bytes(data.physical_bytes)}</div>
      <p class="stat-gloss">On disk after compression.</p>
    </div>
  </div>

  <!-- Compression panel. The ratio + space-saved figures live here now, next to
       the bar that explains them, instead of as duplicate cards above. -->
  <div class="panel comp-panel">
    <div class="comp-head">
      <h2 class="comp-title">Compression</h2>
      <span class="comp-summary"
        >{savedPct}% smaller · {ratio(data.compression_ratio)} ratio</span
      >
    </div>

    <div
      class="comp-bar"
      role="progressbar"
      aria-valuenow={storedPct}
      aria-valuemin="0"
      aria-valuemax="100"
      aria-label={`Stored size: ${bytes(data.physical_bytes)} of ${bytes(
        data.logical_bytes,
      )} original (${savedPct}% saved)`}
    >
      <div class="comp-stored" style:width={`${storedPct}%`}>
        {#if savedPct >= 14}
          <span class="comp-inline-label">Stored {storedPct}%</span>
        {/if}
      </div>
      {#if savedPct > 0}
        <span class="comp-saved-label">Saved {savedPct}%</span>
      {/if}
    </div>

    <dl class="comp-legend">
      <div class="comp-leg-item">
        <dt><i class="swatch stored"></i> Stored</dt>
        <dd class="mono">{bytes(data.physical_bytes)}</dd>
      </div>
      <div class="comp-leg-item">
        <dt><i class="swatch saved"></i> Saved</dt>
        <dd class="mono">{bytes(saved)}</dd>
      </div>
      <div class="comp-leg-item">
        <dt><i class="swatch original"></i> Original</dt>
        <dd class="mono">{bytes(data.logical_bytes)}</dd>
      </div>
    </dl>
  </div>

  <div class="toolbar">
    <h2 class="section-title">Storage by bucket</h2>
    <span class="spacer"></span>
    <button onclick={load} disabled={refreshing} aria-busy={refreshing}>
      {refreshing ? "Refreshing…" : "Refresh"}
    </button>
  </div>

  {#if buckets.length === 0}
    <div class="empty">No buckets yet.</div>
  {:else}
    <div class="panel table-panel">
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Bucket</th>
              <th class="num">Objects</th>
              <th class="num">Original size</th>
              <th class="share-col">Share</th>
            </tr>
          </thead>
          <tbody>
            {#each buckets as b (b.name)}
              <tr>
                <td>
                  <a
                    href={`#/buckets/${b.name}/browser`}
                    class="mono"
                    onclick={(e) => {
                      e.preventDefault();
                      navigate(`/buckets/${b.name}/browser`);
                    }}>{b.name}</a
                  >
                </td>
                <td class="num">{count(b.objects)}</td>
                <td class="num mono">{bytes(b.size)}</td>
                <td>
                  <div
                    class="share-bar"
                    role="progressbar"
                    aria-valuenow={bucketSharePct(b.size)}
                    aria-valuemin="0"
                    aria-valuemax="100"
                    aria-label={`${b.name}: ${bytes(b.size)}, ${bucketSharePct(
                      b.size,
                    )}% of the largest bucket`}
                  >
                    <div
                      class="share-fill"
                      style:width={`${bucketSharePct(b.size)}%`}
                    ></div>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </div>
  {/if}
{/if}

<style>
  /* ---- tiered stat grid ---------------------------------------------------- */
  .tier {
    display: grid;
    gap: 14px;
    margin-bottom: 16px;
  }
  .tier-primary {
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  }
  .tier-storage {
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    margin-bottom: 22px;
  }
  .stat {
    display: flex;
    flex-direction: column;
  }
  /* Primary tier carries the visual weight so the eye lands there first. */
  .stat-lead {
    padding: 20px 22px;
    background: var(--surface);
    border-color: var(--border-strong);
    box-shadow: var(--shadow);
  }
  .stat-lead .value {
    font-size: 2.1rem;
  }
  .stat-gloss {
    margin: 6px 0 0;
    color: var(--text-faint);
    font-size: 0.82rem;
    line-height: 1.35;
  }

  /* ---- compression panel --------------------------------------------------- */
  .comp-panel {
    margin-bottom: 22px;
  }
  .comp-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 12px;
    flex-wrap: wrap;
  }
  .comp-title {
    margin: 0;
  }
  .comp-summary {
    color: var(--text-muted);
    font-size: 0.92rem;
    font-variant-numeric: tabular-nums;
  }

  .comp-bar {
    position: relative;
    height: 28px;
    border-radius: var(--r-sm);
    /* The whole track reads as the "saved" win; the fill is what is actually stored. */
    background: var(--success-tint);
    border: 1px solid var(--success);
    overflow: hidden;
    margin: 14px 0 12px;
  }
  .comp-stored {
    height: 100%;
    background: var(--primary-strong);
    display: flex;
    align-items: center;
    min-width: 2px;
  }
  .comp-inline-label {
    padding-left: 10px;
    color: var(--on-primary);
    font-size: 0.78rem;
    font-weight: 600;
    white-space: nowrap;
  }
  /* The saved portion sits to the right of the fill, labelling the empty track. */
  .comp-saved-label {
    position: absolute;
    top: 50%;
    right: 10px;
    transform: translateY(-50%);
    color: var(--success-ink);
    font-size: 0.78rem;
    font-weight: 600;
    white-space: nowrap;
  }

  .comp-legend {
    display: flex;
    flex-wrap: wrap;
    gap: 10px 26px;
    margin: 0;
  }
  .comp-leg-item {
    display: flex;
    align-items: baseline;
    gap: 8px;
  }
  .comp-leg-item dt {
    color: var(--text-muted);
    font-size: 0.85rem;
  }
  .comp-leg-item dd {
    margin: 0;
    font-size: 0.85rem;
    font-variant-numeric: tabular-nums;
  }
  .swatch {
    display: inline-block;
    width: 10px;
    height: 10px;
    border-radius: 3px;
    margin-right: 4px;
    vertical-align: middle;
  }
  .swatch.stored {
    background: var(--primary-strong);
  }
  .swatch.saved {
    background: var(--success-tint);
    border: 1px solid var(--success);
  }
  .swatch.original {
    background: var(--surface-3);
    border: 1px solid var(--border-strong);
  }

  /* ---- storage-by-bucket table -------------------------------------------- */
  .section-title {
    margin: 0;
  }
  .table-panel {
    padding: 6px 0;
  }
  .share-col {
    width: 34%;
  }
  .share-bar {
    height: 8px;
    border-radius: 999px;
    background: var(--surface-3);
    overflow: hidden;
  }
  .share-fill {
    height: 100%;
    border-radius: 999px;
    background: var(--primary);
  }

  /* ---- loading skeleton spacing ------------------------------------------- */
  .skel-bar {
    margin: 14px 0 12px;
  }

  @media (prefers-reduced-motion: reduce) {
    .comp-stored,
    .share-fill {
      transition: none;
    }
  }
</style>
