// ui/src/views/replication.tsx
// Failed-replication tracker: objects that could not be copied to their
// replication destination after repeated tries. Empty is the good state.

import { CircleAlert, CircleCheck } from "lucide-react";
import { api } from "@/lib/api";
import { whenMs } from "@/lib/format";
import { useResource } from "@/lib/use-resource";
import { DataTable, SkeletonRows, type Column } from "@/components/data-table";
import { EmptyState } from "@/components/empty-state";
import { ErrorAlert } from "@/components/error-alert";
import { Page, PageHeader } from "@/components/page-header";
import { RefreshButton } from "@/components/refresh-button";
import { TableCell, TableRow } from "@/components/ui/table";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";

const SKELETON_ROWS = 4;

const COLUMNS: Column[] = [
  { key: "bucket", label: "Bucket" },
  { key: "key", label: "Key" },
  { key: "version", label: "Version" },
  { key: "attempts", label: "Attempts", className: "text-right" },
  { key: "next", label: "Next attempt" },
  { key: "error", label: "Error" },
];

export function Replication() {
  const res = useResource(() => api.failedReplication(100), []);
  const entries = res.data?.entries ?? [];

  return (
    <Page>
      <PageHeader
        title="Replication"
        description="Objects that failed to replicate to their destination after repeated tries."
        actions={
          <RefreshButton
            loading={res.loading}
            refreshing={res.refreshing}
            onClick={res.refresh}
          />
        }
      />

      {res.error ? (
        <ErrorAlert
          title="Could not load replication status"
          message={res.error}
          onRetry={res.refresh}
        />
      ) : null}

      {res.loading ? (
        <DataTable columns={COLUMNS} minWidth={760}>
          <SkeletonRows
            rows={SKELETON_ROWS}
            widths={["w-24", "w-40", "w-20", "w-10", "w-32", "w-44"]}
          />
        </DataTable>
      ) : entries.length > 0 ? (
        <DataTable columns={COLUMNS} minWidth={760}>
          {entries.map((e, i) => (
            <TableRow key={`${e.bucket}:${e.key}:${e.version_id}:${e.attempts}:${i}`}>
              <TableCell data-label="Bucket" className="font-mono text-[13px]">
                {e.bucket}
              </TableCell>
              <TableCell data-label="Key" className="font-mono text-[13px]">
                <span title={e.key} className="block max-w-[28ch] truncate">
                  {e.key}
                </span>
              </TableCell>
              <TableCell data-label="Version" className="font-mono text-[13px]">
                <span title={e.version_id} className="block max-w-[12ch] truncate">
                  {e.version_id || "—"}
                </span>
              </TableCell>
              <TableCell
                data-label="Attempts"
                className="text-right tabular-nums"
              >
                {e.attempts}
              </TableCell>
              <TableCell
                data-label="Next attempt"
                className="text-muted-foreground tabular-nums"
              >
                {whenMs(e.next_attempt_at_ms)}
              </TableCell>
              <TableCell
                data-label="Error"
                className="text-[13px] text-destructive"
              >
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span
                      title={e.error}
                      className="flex max-w-[32ch] items-center gap-1.5"
                    >
                      <CircleAlert
                        aria-hidden="true"
                        className="size-3.5 shrink-0"
                      />
                      <span className="truncate">{e.error}</span>
                    </span>
                  </TooltipTrigger>
                  <TooltipContent className="max-w-sm break-words">
                    {e.error}
                  </TooltipContent>
                </Tooltip>
              </TableCell>
            </TableRow>
          ))}
        </DataTable>
      ) : !res.error ? (
        <EmptyState
          icon={CircleCheck}
          positive
          title="All caught up"
          body="No failed replication. Objects in buckets with a replication rule are copying normally."
        />
      ) : null}
    </Page>
  );
}

// ui/src/views/Replication.svelte
<script>
  import { api } from "../lib/api.js";
  import { whenMs } from "../lib/format.js";
  import Skeleton from "../components/Skeleton.svelte";

  let entries = $state([]);
  let error = $state("");
  let loading = $state(true);
  let refreshing = $state(false);

  // Show the full skeleton only on first load; later refreshes keep the table visible and just
  // mark the Refresh button busy.
  async function load() {
    if (!loading) refreshing = true;
    error = "";
    try {
      const res = await api.failedReplication(100);
      entries = (res && res.entries) || [];
    } catch (err) {
      error = err.message || "Could not load replication status.";
    } finally {
      loading = false;
      refreshing = false;
    }
  }

  load();

  // A stable key per row: the object identity plus attempt count. Falling back to the index keeps
  // keys unique if two entries ever share the same fields.
  const rowKey = (e, i) =>
    `${e.bucket}:${e.key}:${e.version_id || ""}:${e.attempts}:${i}`;
</script>

<h1>Replication</h1>
<p class="subtitle">
  Objects that could not be copied to your replication target after repeated tries.
</p>

{#if error}
  <div class="notice danger" role="alert">{error}</div>
{/if}

<div class="toolbar">
  <button onclick={load} disabled={refreshing || loading} aria-busy={refreshing}>
    {refreshing ? "Refreshing…" : "Refresh"}
  </button>
</div>

{#if loading}
  <div class="table-wrap" aria-busy="true">
    <Skeleton lines={6} gap="0.9em" />
  </div>
{:else if entries.length === 0}
  <div class="empty">
    <p class="empty-title">No failed replications.</p>
    <p class="empty-body">
      Objects mirror to your target automatically. Anything that cannot be copied after
      several tries will be listed here so you can look into it.
    </p>
  </div>
{:else}
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th>Bucket</th>
          <th>Key</th>
          <th>Version</th>
          <th class="num">Attempts</th>
          <th>Next attempt</th>
          <th>Error</th>
        </tr>
      </thead>
      <tbody>
        {#each entries as e, i (rowKey(e, i))}
          <tr>
            <td class="mono">{e.bucket}</td>
            <td class="mono">{e.key}</td>
            <td class="mono">{e.version_id || "—"}</td>
            <td class="num">{e.attempts}</td>
            <td>{whenMs(e.next_attempt_at_ms)}</td>
            <td class="mono err">{e.error || "—"}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}

<style>
  .err {
    color: var(--danger-ink);
    max-width: 28rem;
    word-break: break-word;
    white-space: normal;
  }
  .empty-title {
    margin: 0 0 4px;
    font-weight: 600;
    color: var(--text);
  }
  .empty-body {
    margin: 0 auto;
    max-width: 34rem;
    font-size: 0.92rem;
    line-height: 1.55;
  }
</style>
