// ui/src/views/users.tsx
// Users are S3-API-only credentials scoped by an access policy. The root admin
// is the sole admin, so there is no role selector here. Create mints an S3
// (SigV4) key/secret shown exactly once and attaches the policy built with the
// PermissionBuilder.

import { useEffect, useId, useState } from "react";
import { NavLink } from "react-router";
import { CircleAlert, Plus, Users as UsersIcon } from "lucide-react";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { CredentialsPanel } from "@/components/credentials-panel";
import { EmptyState } from "@/components/empty-state";
import { Page, PageHeader } from "@/components/page-header";
import { PermissionBuilder } from "@/components/permission-builder";
import { api, errorMessage } from "@/lib/api";
import { useResource } from "@/lib/use-resource";
import type { CreateUserResp } from "@/lib/types";
import type { PolicyDoc } from "@/lib/policy";

export function Users() {
  const nameId = useId();
  const users = useResource(() => api.listUsers(), []);

  const [buckets, setBuckets] = useState<string[]>([]);
  const [bucketsLoading, setBucketsLoading] = useState(true);
  useEffect(() => {
    let alive = true;
    api
      .listBuckets()
      .then((r) => {
        if (alive) setBuckets(r.buckets.map((b) => b.name));
      })
      .catch(() => {
        /* the builder shows its own empty state */
      })
      .finally(() => {
        if (alive) setBucketsLoading(false);
      });
    return () => {
      alive = false;
    };
  }, []);

  const [open, setOpen] = useState(false);
  const [displayName, setDisplayName] = useState("");
  const [nameTouched, setNameTouched] = useState(false);
  // doc from the builder; null = invalid JSON or grants nothing.
  const [doc, setDoc] = useState<PolicyDoc | null>(null);
  const [creating, setCreating] = useState(false);
  // One-time credentials; while set, the dialog refuses to dismiss.
  const [created, setCreated] = useState<CreateUserResp | null>(null);

  const nameError =
    nameTouched && !displayName.trim() ? "Enter a display name." : "";
  const canCreate = !!displayName.trim() && doc !== null && !creating;

  function resetForm() {
    setDisplayName("");
    setNameTouched(false);
    setDoc(null);
  }

  function onOpenChange(next: boolean) {
    // The credentials are shown exactly once: only the explicit Done button
    // (behind the saved acknowledgement) may close the dialog.
    if (!next && created) return;
    setOpen(next);
    if (!next) resetForm();
  }

  async function create(e: React.FormEvent) {
    e.preventDefault();
    setNameTouched(true);
    const dn = displayName.trim();
    if (!dn || doc === null || creating) return;
    setCreating(true);
    try {
      const res = await api.createUser(dn); // member; S3-only
      try {
        await api.setUserPolicy(res.id, JSON.stringify(doc));
      } catch (pe) {
        toast.error(
          `The user was created, but attaching the policy failed: ${errorMessage(pe, "unknown error")}. Attach it from the user's page.`,
        );
      }
      toast.success(`Created ${dn}`);
      setCreated(res);
      users.refresh();
    } catch (err) {
      toast.error(errorMessage(err, "Failed to create the user."));
    } finally {
      setCreating(false);
    }
  }

  function done() {
    setCreated(null);
    setOpen(false);
    resetForm();
  }

  const list = users.data?.users ?? [];

  return (
    <Page>
      <PageHeader
        title="Users"
        description="S3-API access keys, each scoped by an access policy."
        actions={
          <Button onClick={() => setOpen(true)}>
            <Plus aria-hidden="true" /> Create user
          </Button>
        }
      />

      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent
          className="max-h-[85vh] overflow-y-auto sm:max-w-3xl lg:max-w-5xl"
          showCloseButton={!created}
          onInteractOutside={(e) => {
            if (created) e.preventDefault();
          }}
          onEscapeKeyDown={(e) => {
            if (created) e.preventDefault();
          }}
        >
          {created ? (
            <>
              {/* Radix requires a title for the dialog's accessible name. */}
              <DialogHeader className="sr-only">
                <DialogTitle>One-time credentials</DialogTitle>
                <DialogDescription>
                  Save the new user's credentials before closing.
                </DialogDescription>
              </DialogHeader>
              <CredentialsPanel
                fields={[
                  { label: "S3 access key ID", value: created.s3_access_key_id },
                  {
                    label: "S3 secret key",
                    value: created.s3_secret_key,
                    secret: true,
                  },
                  {
                    label: "Bearer token (management API)",
                    value: `${created.bearer_access_key_id}.${created.bearer_secret}`,
                    secret: true,
                  },
                ]}
                explainer={
                  <>
                    Most clients use the <strong>S3 key and secret</strong> — any
                    S3 tool (boto3, aws-cli, rclone) signs with them against this
                    server. The <strong>Bearer token</strong> is an alternative
                    for Cairn's own API and tools; it cannot open this console,
                    which is admin-only.
                  </>
                }
                onDone={done}
              />
            </>
          ) : (
            <>
              <DialogHeader>
                <DialogTitle>Create user</DialogTitle>
                <DialogDescription>
                  New users can only call the S3 API with their keys. They cannot
                  sign in to this console.
                </DialogDescription>
              </DialogHeader>
              <form onSubmit={create} className="space-y-5">
                <div className="space-y-1.5">
                  <Label htmlFor={nameId}>Display name</Label>
                  <Input
                    id={nameId}
                    value={displayName}
                    placeholder="e.g. backup-bot"
                    autoComplete="off"
                    onChange={(e) => setDisplayName(e.target.value)}
                    onBlur={() => setNameTouched(true)}
                    aria-invalid={nameError ? true : undefined}
                    aria-describedby={nameError ? `${nameId}-err` : undefined}
                  />
                  {nameError ? (
                    <p
                      id={`${nameId}-err`}
                      role="alert"
                      className="text-[13px] text-destructive"
                    >
                      {nameError}
                    </p>
                  ) : null}
                </div>

                <div className="space-y-1.5">
                  <p className="text-sm font-medium">Access policy</p>
                  <p className="text-[13px] text-muted-foreground">
                    Choose what this user's S3 credentials can do. The Builder
                    uses plain choices; switch to Split or Code to edit the
                    policy JSON directly.
                  </p>
                  <PermissionBuilder
                    buckets={buckets}
                    bucketsLoading={bucketsLoading}
                    onChange={setDoc}
                  />
                </div>

                {doc === null ? (
                  <p className="text-[13px] text-destructive" role="alert">
                    This policy grants nothing or the JSON is invalid. Fix it
                    above before creating the user.
                  </p>
                ) : null}

                <div className="flex justify-end gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => onOpenChange(false)}
                  >
                    Cancel
                  </Button>
                  <Button type="submit" disabled={!canCreate}>
                    {creating ? "Creating…" : "Create user"}
                  </Button>
                </div>
              </form>
            </>
          )}
        </DialogContent>
      </Dialog>

      {users.error ? (
        <Alert variant="destructive" className="mb-4" role="alert">
          <CircleAlert aria-hidden="true" />
          <AlertTitle>Could not load users</AlertTitle>
          <AlertDescription>
            {users.error}
            <Button
              variant="outline"
              size="sm"
              onClick={users.refresh}
              className="mt-2"
            >
              Try again
            </Button>
          </AlertDescription>
        </Alert>
      ) : null}

      {users.loading ? (
        <UsersTableShell>
          {[0, 1, 2].map((i) => (
            <TableRow key={i}>
              <TableCell>
                <Skeleton className="h-4 w-32" />
              </TableCell>
              <TableCell>
                <Skeleton className="h-4 w-44" />
              </TableCell>
              <TableCell>
                <Skeleton className="h-4 w-16" />
              </TableCell>
              <TableCell>
                <Skeleton className="h-4 w-14" />
              </TableCell>
            </TableRow>
          ))}
        </UsersTableShell>
      ) : list.length === 0 && !users.error ? (
        <EmptyState
          icon={UsersIcon}
          title="No users yet"
          body="Create one to mint an S3 access key scoped to the buckets and actions you choose."
          action={
            <Button onClick={() => setOpen(true)}>
              <Plus aria-hidden="true" /> Create user
            </Button>
          }
        />
      ) : list.length > 0 ? (
        <UsersTableShell>
          {list.map((u) => (
            <TableRow key={u.id}>
              <TableCell>
                <NavLink
                  to={`/users/${encodeURIComponent(u.id)}`}
                  className="text-link hover:underline underline-offset-4"
                >
                  {u.display_name}
                </NavLink>
              </TableCell>
              <TableCell className="font-mono text-[13px]">
                {u.access_key_id}
              </TableCell>
              <TableCell>
                <Badge variant="outline">{u.role}</Badge>
              </TableCell>
              <TableCell>
                {u.is_active ? (
                  <Badge variant="outline">Active</Badge>
                ) : (
                  <Badge variant="outline" className="text-muted-foreground">
                    Inactive
                  </Badge>
                )}
              </TableCell>
            </TableRow>
          ))}
        </UsersTableShell>
      ) : null}
    </Page>
  );
}

function UsersTableShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="overflow-x-auto rounded-lg border">
      <Table className="min-w-[560px]">
        <TableHeader>
          <TableRow>
            <TableHead className="text-xs text-muted-foreground">Name</TableHead>
            <TableHead className="text-xs text-muted-foreground">
              Bearer key
            </TableHead>
            <TableHead className="text-xs text-muted-foreground">Role</TableHead>
            <TableHead className="text-xs text-muted-foreground">
              Status
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>{children}</TableBody>
      </Table>
    </div>
  );
}

// ui/src/views/Users.svelte
<script>
  // Users are S3-API-only credentials scoped by an access policy. The root admin is the sole admin,
  // so there is no role selector here. Create mints an S3 (SigV4) key/secret shown exactly once and
  // attaches the policy built with the PermissionBuilder.
  import { tick } from "svelte";
  import { api } from "../lib/api.js";
  import { navigate } from "../lib/router.js";
  import { ok, err } from "../lib/toast.js";
  import PermissionBuilder from "../components/PermissionBuilder.svelte";
  import CopyField from "../components/CopyField.svelte";
  import Skeleton from "../components/Skeleton.svelte";

  let users = $state([]);
  let buckets = $state([]);
  let loading = $state(true);
  let bucketsLoading = $state(true);

  let showCreate = $state(false);
  let displayName = $state("");
  let nameTouched = $state(false);
  let pendingPolicy = $state(undefined); // doc from the builder; null = invalid or grants nothing
  let creating = $state(false);
  let created = $state(null); // one-time credentials
  let savedAck = $state(false); // user confirmed they stored the one-time secret
  let createdPanel = $state(null); // element to focus when credentials appear

  // Inline, pre-submit validity so the button state explains itself instead of waiting for a toast.
  let nameError = $derived(nameTouched && !displayName.trim() ? "Enter a display name." : "");
  let policyInvalid = $derived(pendingPolicy === null);
  let canCreate = $derived(!!displayName.trim() && !policyInvalid && !creating);

  async function load() {
    loading = true;
    bucketsLoading = true;
    try {
      const res = await api.listUsers();
      users = (res && res.users) || [];
    } catch (e) {
      err(e.message);
    }
    loading = false;
    try {
      const b = await api.listBuckets();
      buckets = (b.buckets || []).map((x) => x.name);
    } catch (e) {
      err(e.message);
    }
    bucketsLoading = false;
  }
  load();

  const onPolicy = (doc) => (pendingPolicy = doc);

  async function create() {
    nameTouched = true;
    const dn = displayName.trim();
    if (!dn) return;
    if (policyInvalid) return; // button is disabled; guard anyway
    creating = true;
    try {
      const res = await api.createUser(dn); // member; S3-only
      if (pendingPolicy) await api.setUserPolicy(res.id, JSON.stringify(pendingPolicy));
      created = res;
      savedAck = false;
      ok(`Created ${dn}`);
      showCreate = false;
      displayName = "";
      nameTouched = false;
      await load();
      await tick();
      createdPanel?.focus();
    } catch (e) {
      err(e.message);
    }
    creating = false;
  }

  function dismissCreated() {
    created = null;
    savedAck = false;
  }
</script>

<div class="row" style="justify-content:space-between; align-items:center;">
  <div>
    <h1 style="margin-bottom:2px">Users</h1>
    <p class="subtitle" style="margin:0">S3-API access keys, each scoped by an access policy.</p>
  </div>
  <button class="btn primary" onclick={() => (showCreate = !showCreate)}>
    {showCreate ? "Cancel" : "New user"}
  </button>
</div>

{#if created}
  <!-- One-time credentials: a focused, high-gravity panel that cannot be dismissed by accident. It
       takes focus on appear, is labelled as an alert, and only the explicit "I have saved these"
       acknowledgement enables Done. -->
  <section
    class="cred-panel"
    bind:this={createdPanel}
    tabindex="-1"
    role="group"
    aria-live="assertive"
    aria-labelledby="cred-title"
    aria-describedby="cred-desc">
    <h2 id="cred-title" class="cred-title">Save these credentials now</h2>
    <p id="cred-desc" class="cred-desc">
      The secret key is shown only once and cannot be retrieved later. Store it somewhere safe before
      you close this. These are S3 credentials: use them in any S3 client (boto3, aws-cli, and
      others) against this server.
    </p>

    <CopyField label="S3 access key id" value={created.s3_access_key_id} secret={true} />
    <CopyField label="S3 secret key" value={created.s3_secret_key} secret={true} />

    <details class="cred-advanced">
      <summary>Other ways to authenticate</summary>
      <p class="cred-adv-note">
        Most clients use the S3 key and secret above. This token is an alternative used by Cairn's own
        API and tools that authenticate with a single bearer token instead of an S3 key pair.
      </p>
      <CopyField
        label="Bearer token"
        value={`${created.bearer_access_key_id}.${created.bearer_secret}`}
        secret={true} />
    </details>

    <label class="cred-ack check">
      <input type="checkbox" bind:checked={savedAck} />
      <span>I have saved these credentials.</span>
    </label>

    <div class="row" style="gap:8px; margin-top:4px;">
      <button class="btn primary" disabled={!savedAck} onclick={dismissCreated}>Done</button>
    </div>
  </section>
{/if}

{#if showCreate}
  <div class="card" style="margin-top:16px">
    <h2 style="margin-top:0">New user</h2>
    <div class="field">
      <label for="dn">Display name</label>
      <input
        id="dn"
        placeholder="e.g. backup-bot"
        bind:value={displayName}
        onblur={() => (nameTouched = true)}
        class:invalid={!!nameError}
        aria-invalid={!!nameError}
        aria-describedby={nameError ? "dn-err" : undefined}
        autocomplete="off" />
      {#if nameError}<span id="dn-err" class="field-error" role="alert">{nameError}</span>{/if}
    </div>

    <div class="label-sm" style="margin-top:14px">Access policy</div>
    <p class="muted" style="margin-top:2px">
      Choose what this user's S3 credentials can do. The Builder uses plain choices; switch to Split
      or Code if you prefer to edit the policy JSON directly.
    </p>
    <PermissionBuilder {buckets} {bucketsLoading} onchange={onPolicy} />

    {#if policyInvalid}
      <p class="field-error" role="alert" style="margin-top:10px">
        This policy grants nothing or the JSON is invalid. Fix it above before creating the user.
      </p>
    {/if}

    <div class="row" style="gap:8px; margin-top:14px;">
      <button class="btn primary" onclick={create} disabled={!canCreate}>
        {creating ? "Creating…" : "Create user"}
      </button>
      <button class="btn" onclick={() => (showCreate = false)}>Cancel</button>
    </div>
  </div>
{/if}

{#if loading}
  <div class="table-wrap" style="margin-top:16px" aria-busy="true">
    <table>
      <thead>
        <tr>
          <th>Display name</th>
          <th>S3 access key</th>
          <th>Status</th>
          <th style="text-align:right;"></th>
        </tr>
      </thead>
      <tbody>
        {#each Array(3) as _, i (i)}
          <tr>
            <td><Skeleton lines={1} width="60%" /></td>
            <td><Skeleton lines={1} width="80%" /></td>
            <td><Skeleton lines={1} width="40%" /></td>
            <td></td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{:else if users.length === 0}
  <div class="empty" style="margin-top:16px">
    No users yet. Create one to mint an S3 access key scoped to the buckets and actions you choose.
  </div>
{:else}
  <div class="table-wrap" style="margin-top:16px">
    <table>
      <thead>
        <tr>
          <th>Display name</th>
          <th>S3 access key</th>
          <th>Status</th>
          <th style="text-align:right;"></th>
        </tr>
      </thead>
      <tbody>
        {#each users as u (u.id)}
          <tr>
            <td>
              <a
                href={`#/users/${encodeURIComponent(u.id)}`}
                onclick={(e) => {
                  e.preventDefault();
                  navigate(`/users/${encodeURIComponent(u.id)}`);
                }}>{u.display_name}</a>
            </td>
            <td class="mono">{u.access_key_id}</td>
            <td>
              <span class="badge" class:success={u.is_active}
                >{u.is_active ? "active" : "inactive"}</span>
            </td>
            <td style="text-align:right;">
              <button class="btn" onclick={() => navigate(`/users/${encodeURIComponent(u.id)}`)}>
                Manage
              </button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}

<style>
  .cred-panel {
    margin-top: 16px;
    background: var(--surface);
    border: 2px solid var(--warning);
    border-radius: var(--r-lg);
    padding: 20px 22px;
    box-shadow: var(--shadow);
  }
  .cred-panel:focus-visible {
    outline: 3px solid var(--ring-color);
    outline-offset: 2px;
  }
  .cred-title {
    margin: 0 0 6px;
    font-size: 1.15rem;
  }
  .cred-desc {
    margin: 0 0 16px;
    color: var(--text-muted);
    font-size: 0.92rem;
    line-height: 1.55;
  }
  .cred-advanced {
    margin: 6px 0 14px;
  }
  .cred-advanced summary {
    cursor: pointer;
    font-size: 0.88rem;
    color: var(--link);
    font-weight: 500;
    padding: 4px 0;
  }
  .cred-adv-note {
    margin: 8px 0 10px;
    font-size: 0.85rem;
    color: var(--text-muted);
    line-height: 1.5;
  }
  .cred-ack {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 4px 0 14px;
    font-size: 0.92rem;
    cursor: pointer;
    font-weight: 500;
  }
  .cred-ack input {
    width: 16px;
    height: 16px;
  }
</style>
